# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedMolecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdf_info', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('smiles', models.CharField(max_length=255)),
                ('pdb_info', models.FileField(max_length=255, upload_to=b'pdbs/')),
            ],
        ),
        migrations.CreateModel(
            name='ComputedSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('submitted_sdf', models.FileField(max_length=255, upload_to=b'compound_sets/')),
                ('spec_version', models.FloatField()),
                ('method_url', models.TextField(max_length=1000, null=True)),
                ('unique_name', models.CharField(max_length=101)),
            ],
        ),
        migrations.CreateModel(
            name='ComputedSetSubmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=50)),
                ('generation_date', models.DateField()),
                ('method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DesignSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=50)),
                ('set_type', models.CharField(choices=[(b'library', b'library'), (b'follow-up', b'follow-up'), (b'user-submitted', b'user-submitted'), (b'enumerated', b'enumerated')], default=b'user-submitted', max_length=100)),
                ('set_description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMolecule',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('smiles', models.CharField(db_index=True, max_length=255, null=True)),
                ('lig_id', models.CharField(max_length=5, null=True)),
                ('chain_id', models.CharField(max_length=1, null=True)),
                ('mol_type', models.CharField(choices=[(b'PR', b'Proasis molecule'), (b'SD', b'Sdf molecule'), (b'HA', b'Hydrogens added '), (b'HC', b'Mol2 format with Hydrogens and AM1 BCC')], default=b'PR', max_length=2)),
                ('sdf_info', models.TextField(null=True)),
                ('rscc', models.FloatField(null=True)),
                ('occupancy', models.FloatField(null=True)),
                ('x_com', models.FloatField(null=True)),
                ('y_com', models.FloatField(null=True)),
                ('z_com', models.FloatField(null=True)),
                ('rmsd', models.FloatField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical molecule',
            },
        ),
        migrations.RemoveField(
            model_name='compoundset',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='compoundset',
            name='target',
        ),
        migrations.DeleteModel(
            name='CompoundSetSubmitter',
        ),
        migrations.RemoveField(
            model_name='computedcompound',
            name='compound_set',
        ),
        migrations.RemoveField(
            model_name='computedcompound',
            name='inspiration_frags',
        ),
        migrations.RemoveField(
            model_name='scoredescription',
            name='compound_set',
        ),
        migrations.AddField(
            model_name='compound',
            name='all_identifiers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='current_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='inspirations',
            field=models.ManyToManyField(blank=True, null=True, to='viewer.Molecule'),
        ),
        migrations.AddField(
            model_name='compound',
            name='long_inchi',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='csetkeys',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csetkeys',
            name='user',
            field=models.CharField(default=b'User', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='csetkeys',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='numericalscorevalues',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.ComputedMolecule'),
        ),
        migrations.AlterField(
            model_name='textscorevalues',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.ComputedMolecule'),
        ),
        migrations.AlterUniqueTogether(
            name='csetkeys',
            unique_together=set([('user', 'uuid')]),
        ),
        migrations.DeleteModel(
            name='CompoundSet',
        ),
        migrations.DeleteModel(
            name='ComputedCompound',
        ),
        migrations.AddField(
            model_name='historicalmolecule',
            name='cmpd_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viewer.Compound'),
        ),
        migrations.AddField(
            model_name='historicalmolecule',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmolecule',
            name='prot_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viewer.Protein'),
        ),
        migrations.AddField(
            model_name='designset',
            name='compounds',
            field=models.ManyToManyField(to='viewer.Compound'),
        ),
        migrations.AlterUniqueTogether(
            name='computedsetsubmitter',
            unique_together=set([('name', 'method')]),
        ),
        migrations.AddField(
            model_name='computedset',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.ComputedSetSubmitter'),
        ),
        migrations.AddField(
            model_name='computedset',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Target'),
        ),
        migrations.AddField(
            model_name='computedmolecule',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Compound'),
        ),
        migrations.AddField(
            model_name='computedmolecule',
            name='computed_inspirations',
            field=models.ManyToManyField(blank=True, null=True, to='viewer.Molecule'),
        ),
        migrations.AddField(
            model_name='computedmolecule',
            name='computed_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.ComputedSet'),
        ),
        migrations.AddField(
            model_name='scoredescription',
            name='computed_set',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='viewer.ComputedSet'),
            preserve_default=False,
        ),
    ]
