# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-04 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_target_zip_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypoint',
            name='operator',
            field=models.CharField(default='NA', max_length=5),
        ),
        migrations.AlterField(
            model_name='computedmolecule',
            name='pdb_info',
            field=models.FileField(max_length=255, upload_to='pdbs/'),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='submitted_sdf',
            field=models.FileField(max_length=255, upload_to='compound_sets/'),
        ),
        migrations.AlterField(
            model_name='csetkeys',
            name='user',
            field=models.CharField(default='User', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='designset',
            name='set_type',
            field=models.CharField(choices=[('library', 'library'), ('follow-up', 'follow-up'), ('user-submitted', 'user-submitted'), ('enumerated', 'enumerated')], default='user-submitted', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='historicalmolecule',
            name='mol_type',
            field=models.CharField(choices=[('PR', 'Proasis molecule'), ('SD', 'Sdf molecule'), ('HA', 'Hydrogens added '), ('HC', 'Mol2 format with Hydrogens and AM1 BCC')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='mol_type',
            field=models.CharField(choices=[('PR', 'Proasis molecule'), ('SD', 'Sdf molecule'), ('HA', 'Hydrogens added '), ('HC', 'Mol2 format with Hydrogens and AM1 BCC')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='protein',
            name='bound_info',
            field=models.FileField(max_length=255, null=True, upload_to='bound/'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='cif_info',
            field=models.FileField(max_length=255, null=True, upload_to='cifs/'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='map_info',
            field=models.FileField(max_length=255, null=True, upload_to='maps/'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='mtz_info',
            field=models.FileField(max_length=255, null=True, upload_to='mtzs/'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='pdb_info',
            field=models.FileField(max_length=255, null=True, upload_to='pdbs/'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='prot_type',
            field=models.CharField(choices=[('AP', 'Apo'), ('ST', 'Stripped'), ('TL', 'Tleaped'), ('CH', 'Chunked'), ('BO', 'Bound')], default='AP', max_length=2),
        ),
        migrations.AlterField(
            model_name='sessionproject',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sessionproject',
            name='tags',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='type',
            field=models.CharField(choices=[('INIT', 'INIT'), ('AUTO', 'AUTO'), ('MANUAL', 'MANUAL')], default='INIT', max_length=8),
        ),
        migrations.AlterField(
            model_name='target',
            name='metadata',
            field=models.FileField(max_length=255, null=True, upload_to='metadata/'),
        ),
        migrations.AlterField(
            model_name='target',
            name='zip_archive',
            field=models.FileField(max_length=255, null=True, upload_to='archive/'),
        ),
    ]
