# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_target_zip_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='zip_archive',
            field=models.FileField(max_length=255, null=True, upload_to=b'targets/'),
        ),
    ]
