# Generated by Django 3.2.20 on 2023-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0003_auto_20230818_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonsite',
            name='canon_site_id',
            field=models.TextField(help_text='canon_site id from YAML'),
        ),
        migrations.AlterField(
            model_name='xtalform',
            name='xtalform_id',
            field=models.TextField(help_text='xtalform id from YAML', null=True),
        ),
        migrations.AlterField(
            model_name='xtalformsite',
            name='xtalform_site_id',
            field=models.TextField(help_text='xtalform site id from YAML'),
        ),
    ]
