# Generated by Django 3.2.20 on 2023-08-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20230823_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xtalform',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='xtalform',
            name='quat_assembly',
        ),
        migrations.AddField(
            model_name='experiment',
            name='xtalform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewer.xtalform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experimentupload',
            name='task_id',
            field=models.UUIDField(null=True),
        ),
        migrations.CreateModel(
            name='XtalformQuatAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_id', models.TextField()),
                ('chains', models.TextField()),
                ('quat_assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.quatassembly')),
                ('xtalform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.xtalform')),
            ],
        ),
        migrations.AddField(
            model_name='xtalform',
            name='compounds',
            field=models.ManyToManyField(through='viewer.XtalformQuatAssembly', to='viewer.QuatAssembly'),
        ),
    ]
