# Generated by Django 3.1 on 2020-10-02 14:04

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0004_auto_20200804_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'viewer_actiontype',
            },
        ),
        migrations.CreateModel(
            name='SnapshotActions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('actions', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.sessionproject')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.snapshot')),
            ],
            options={
                'db_table': 'viewer_snapshotactions',
            },
        ),
        migrations.CreateModel(
            name='SessionActions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('actions', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.sessionproject')),
            ],
            options={
                'db_table': 'viewer_sessionactions',
            },
        ),
    ]
