# Generated by Django 3.2.20 on 2023-08-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_auto_20230829_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xtalform',
            old_name='compounds',
            new_name='quat_assembly',
        ),
    ]
