# Generated by Django 3.1 on 2021-02-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20210205_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='inchi',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='compound',
            unique_together={('inchi', 'long_inchi')},
        ),
    ]
