# Generated by Django 3.1 on 2021-04-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_auto_20210206_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='diff_info',
            field=models.FileField(max_length=255, null=True, upload_to='maps/'),
        ),
        migrations.AddField(
            model_name='protein',
            name='event_info',
            field=models.FileField(max_length=255, null=True, upload_to='maps/'),
        ),
        migrations.AddField(
            model_name='protein',
            name='sigmaa_info',
            field=models.FileField(max_length=255, null=True, upload_to='maps/'),
        ),
    ]
