# Generated by Django 3.1 on 2021-04-13 15:52

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_auto_20200804_1411'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0008_auto_20210206_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
                ('colour', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'viewer_tagcategory',
            },
        ),
        migrations.CreateModel(
            name='SessionProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, unique=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('colour', models.CharField(max_length=20, null=True)),
                ('discourse_url', models.TextField(max_length=1000, null=True)),
                ('help_text', models.TextField(null=True)),
                ('additional_info', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.tagcategory')),
                ('session_projects', models.ManyToManyField(to='viewer.SessionProject')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.target')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoleculeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, unique=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('colour', models.CharField(max_length=20, null=True)),
                ('discourse_url', models.TextField(max_length=1000, null=True)),
                ('help_text', models.TextField(null=True)),
                ('additional_info', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.tagcategory')),
                ('mol_groups', models.ManyToManyField(blank=True, to='scoring.MolGroup')),
                ('molecules', models.ManyToManyField(blank=True, to='viewer.Molecule')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.target')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
