# Generated by Django 3.1 on 2021-04-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_auto_20200804_1411'),
        ('viewer', '0010_auto_20210414_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moleculetag',
            name='mol_groups',
        ),
        migrations.AddField(
            model_name='moleculetag',
            name='mol_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoring.molgroup'),
        ),
    ]
