# Generated by Django 3.1 on 2021-04-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_auto_20210407_1345'),
        ('viewer', '0012_auto_20210420_1224'),
    ]

    operations = [
    ]
