# Generated by Django 3.2.20 on 2023-09-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_alter_experimentupload_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='heavy_atom_count',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='heavy_atom_mol_wt',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='mol_log_p',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='mol_wt',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='nhoh_count',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='no_count',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='num_h_acceptors',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='num_h_donors',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='num_het_atoms',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='num_rot_bonds',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='num_val_electrons',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='ring_count',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='tpsa',
        ),
    ]
