# Generated by Django 3.2.20 on 2023-10-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0013_auto_20230921_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteObvsSiteObservationTag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'site_observation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.siteobservation',
                    ),
                ),
                (
                    'site_obvs_tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.siteobservationtag',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='siteobvssiteobservationtag',
            constraint=models.UniqueConstraint(
                fields=('site_observation', 'site_obvs_tag'),
                name='unique_siteobservationtagcontents',
            ),
        ),
    ]
