# Generated by Django 3.1 on 2021-04-21 14:38

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_merge_20210421_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moleculetag',
            name='additional_info',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='sessionprojecttag',
            name='additional_info',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
