# Generated by Django 3.1 on 2021-04-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_auto_20210421_1438'),
    ]

    def insertTagData(apps, schema_editor):
        TagCategory = apps.get_model('viewer', 'TagCategory')
        tag_cat = TagCategory(category = "Sites", colour = "00CC00", description = None)
        tag_cat.save()
        tag_cat = TagCategory(category = "Series", colour = "0000CC", description = None)
        tag_cat.save()
        tag_cat = TagCategory(category = "Forum", colour = "CC0000", description = None)
        tag_cat.save()
        tag_cat = TagCategory(category = "Other", colour = "000000", description = None)
        tag_cat.save()

    operations = [
        migrations.RunPython(insertTagData),
    ]

