# Generated by Django 3.1 on 2021-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_auto_20210422_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmolecule',
            name='sdf_file',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='sdf_file',
            field=models.FileField(max_length=255, null=True, upload_to='sdfs/'),
        ),
        migrations.AddField(
            model_name='protein',
            name='trans_matrix_info',
            field=models.FileField(max_length=255, null=True, upload_to='trans/'),
        ),
    ]
