# Generated by Django 3.2.20 on 2023-11-02 16:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_auto_20231023_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentupload',
            name='message',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Any message or task info associated with the upload. Used for upload audit trail', null=True),
        ),
    ]
