# Generated by Django 3.1 on 2021-12-14 09:46

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0016_auto_20211005_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(db_index=True, max_length=200, unique=True)),
                ('proteins', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('protein_params', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('other_params', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('static_link', models.BooleanField(default=False)),
                ('zip_contents', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('keep_zip_until', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('zip_file', models.BooleanField(default=False)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.target')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'viewer_downloadlinks',
            },
        ),
    ]
