# Generated by Django 3.1 on 2021-12-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_downloadlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlinks',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='downloadlinks',
            name='keep_zip_until',
            field=models.DateTimeField(db_index=True),
        ),
    ]
