# Generated by Django 3.2.20 on 2023-11-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_alter_experimentupload_message'),
    ]

    operations = [
    ]
