# Generated by Django 3.2.20 on 2023-11-07 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0019_auto_20231110_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfiletransfer',
            name='transfer_spec',
        ),
    ]
