# Generated by Django 3.1 on 2022-01-27 13:39

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_auto_20220111_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlinks',
            name='original_search',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
