# Generated by Django 3.1 on 2022-03-17 15:50

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0020_downloadlinks_original_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='apo_desolve_info',
            field=models.FileField(max_length=255, null=True, upload_to='pdbs/'),
        ),
        migrations.AddField(
            model_name='protein',
            name='pdb_header_info',
            field=models.FileField(max_length=255, null=True, upload_to='pdbs/'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='additional_info',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='default_squonk_project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='upload_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='upload_progress',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='upload_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='upload_task_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('squonk_job_name', models.CharField(max_length=200, null=True)),
                ('squonk_project', models.CharField(max_length=200, null=True)),
                ('squonk_job_spec', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('job_status', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED')], default='PENDING', max_length=7)),
                ('squonk_job_info', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('squonk_url_ext', models.CharField(max_length=200, null=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('upload_task_id', models.CharField(max_length=50, null=True)),
                ('upload_status', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED')], default='PENDING', max_length=7, null=True)),
                ('computed_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.computedset')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.snapshot')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.target')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'viewer_jobrequest',
            },
        ),
        migrations.CreateModel(
            name='JobFileTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('squonk_project', models.CharField(max_length=200, null=True)),
                ('proteins', models.CharField(max_length=5000, null=True)),
                ('compounds', models.CharField(max_length=5000, null=True)),
                ('transfer_spec', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('transfer_task_id', models.CharField(max_length=50, null=True)),
                ('transfer_status', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED')], default='PENDING', max_length=7)),
                ('transfer_progress', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('transfer_datetime', models.DateTimeField(null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.snapshot')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.target')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'viewer_jobfiletransfer',
            },
        ),
    ]
