# Generated by Django 3.2.20 on 2023-11-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_remove_jobfiletransfer_transfer_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computedmolecule',
            name='site_observation',
        ),
        migrations.AddField(
            model_name='computedmolecule',
            name='computed_inspirations',
            field=models.ManyToManyField(blank=True, to='viewer.SiteObservation'),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='spec_version',
            field=models.FloatField(help_text='The version of the SDF file format specification'),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='submitted_sdf',
            field=models.FileField(help_text='The SDF file containing the computed set', max_length=255, upload_to='computed_set_sdfs/'),
        ),
    ]
