# Generated by Django 3.1 on 2022-03-25 11:23

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0021_auto_20220317_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfiletransfer',
            name='compounds',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='jobfiletransfer',
            name='proteins',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
