# Generated by Django 3.2.20 on 2023-12-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0021_fix_computedset_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedmolecule',
            name='rationale',
            field=models.TextField(
                blank=True,
                help_text='An optional rationale for this molecule',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='computedmolecule',
            name='ref_url',
            field=models.TextField(
                blank=True,
                help_text='An optional url linking to the reference for this molecule',
                null=True,
            ),
        ),
    ]
