# Generated by Django 3.1 on 2022-05-09 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0022_auto_20220325_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedset',
            name='owner_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='computedset',
            name='upload_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='computedset',
            name='upload_progress',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='computedset',
            name='upload_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='computedset',
            name='upload_task_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='job_status_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
