# Generated by Django 3.2.20 on 2023-12-14 12:04

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0022_add_computedMolecule_rationale'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedmolecule',
            name='identifier',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet='ACDEFGHJKLMNPRSTUVWXYZ23456789',
                blank=True,
                help_text="A four character string of non-confusing uppercase letters and digits for easy reference. This is combined with the Target to form the ComputedMolecule's name",
                length=4,
                max_length=4,
                null=True,
                prefix='',
            ),
        ),
        migrations.AddField(
            model_name='computedmolecule',
            name='molecule_name',
            field=models.CharField(
                blank=True,
                help_text='Set from the _Name property of the underlying Molecule',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='computedmolecule',
            name='name',
            field=models.CharField(
                help_text='A combination of Target and Identifier', max_length=50
            ),
        ),
    ]
