# Generated by Django 3.2.20 on 2023-12-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0023_add_identity_and_moleculename_to_computedmolecule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computedset',
            name='unique_name',
        ),
        migrations.AddField(
            model_name='computedset',
            name='md_ordinal',
            field=models.SmallIntegerField(
                blank=True,
                help_text='The ordinal distinguishing between uploads using the same method and date',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='computedset',
            name='method',
            field=models.CharField(
                blank=True,
                help_text='The name of the algorithmic method used to generate the compounds (e.g. Fragmenstein)',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='computedset',
            name='upload_date',
            field=models.DateField(
                blank=True, help_text='The date the set was uploaded', null=True
            ),
        ),
        migrations.AddField(
            model_name='computedset',
            name='written_sdf_filename',
            field=models.TextField(
                help_text='The written ComputedSet filename', max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='submitted_sdf',
            field=models.FileField(
                help_text='The original SDF containing the ComputedSet',
                max_length=255,
                upload_to='computed_set_data/',
            ),
        ),
    ]
