# Generated by Django 3.1.14 on 2022-06-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0023_job_launcher_phase_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='job_finish_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='job_start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
