# Generated by Django 3.2.20 on 2023-12-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0024_modified_computedset'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedset',
            name='written_sdf_filename',
            field=models.TextField(
                help_text='The written ComputedSet filename', max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='submitted_sdf',
            field=models.FileField(
                help_text='The original SDF containing the ComputedSet',
                max_length=255,
                upload_to='computed_set_data/',
            ),
        ),
    ]
