# Generated by Django 3.2.23 on 2023-12-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0025_increase_length_of_computedset_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedmolecule',
            name='lhs_pdb',
            field=models.TextField(
                blank=True,
                help_text='Set from the lhs_pdb or ref_pdb property of the underlying Molecule',
                max_length=50,
                null=True,
            ),
        ),
    ]
