# Generated by Django 3.1.14 on 2023-01-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0025_squonk2org_squonk2project_squonk2unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='open_to_public',
            field=models.BooleanField(default=False),
        ),
    ]
