# Generated by Django 3.2.23 on 2023-12-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0026_add_lhs_pdb_to_computedmolecule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computedmolecule',
            name='lhs_pdb',
        ),
        migrations.AddField(
            model_name='computedmolecule',
            name='site_observation_code',
            field=models.TextField(
                blank=True,
                help_text='The LHS SiteObservation for this molecule',
                null=True,
            ),
        ),
    ]
