# Generated by Django 3.1.14 on 2023-01-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0026_add_project_open_to_public_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.project'),
        ),
    ]
