# Generated by Django 3.1.14 on 2023-03-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0027_sessionproject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.project'),
        ),
    ]
