# Generated by Django 3.2.23 on 2024-01-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0028_auto_20240108_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='display_name',
            field=models.TextField(blank=True),
        ),
    ]
