# Generated by Django 3.1.14 on 2023-04-21 14:06

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0029_add_job_request_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfiletransfer',
            name='sub_path',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', length=4, max_length=4, prefix=''),
        ),
    ]
