# Generated by Django 3.1.14 on 2023-04-24 10:15

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0030_jobfiletransfer_sub_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfiletransfer',
            name='sub_path',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', length=4, max_length=4, null=True, prefix=''),
        ),
    ]
