# Generated by Django 3.2.23 on 2024-01-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0030_add_cm_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='compound_code',
            field=models.TextField(null=True),
        ),
    ]
