# Generated by Django 3.1.14 on 2023-05-31 13:44

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0031_fix_JobFileTransfer_sub_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('author', models.ForeignKey(help_text='The user that uploaded the override', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'viewer_joboverride',
            },
        ),
    ]
