# Generated by Django 3.2.23 on 2024-01-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0032_auto_20240119_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteobservation',
            name='cmpd',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='viewer.compound',
            ),
        ),
    ]
