# Generated by Django 3.1.14 on 2023-06-29 11:30

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0033_initial_xch_upload_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfiletransfer',
            name='sub_path',
        ),
        migrations.AlterField(
            model_name='compound',
            name='inspirations',
            field=models.ManyToManyField(blank=True, help_text='Foreign key link to any number of 3D Molecules that inspired the design of this compound', to='viewer.Molecule'),
        ),
        migrations.AlterField(
            model_name='computedmolecule',
            name='computed_inspirations',
            field=models.ManyToManyField(blank=True, help_text='Existing fragalysis molecules that were inspirations in the design/calculation of the molecule', to='viewer.Molecule'),
        ),
        migrations.AlterField(
            model_name='jobfiletransfer',
            name='compounds',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='jobfiletransfer',
            name='proteins',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='jobfiletransfer',
            name='squonk_project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobfiletransfer',
            name='transfer_spec',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='jobfiletransfer',
            name='transfer_task_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='aligned',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='apo_holo',
            field=models.BooleanField(help_text='0 for apo (ligand removed), 1 for holo (ligand in tact)', null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='has_eds',
            field=models.BooleanField(null=True),
        ),
    ]
