# Generated by Django 3.1.14 on 2023-07-05 14:05

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0034_auto_20230629_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('residues', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('canon_site_id', models.IntegerField(help_text='canon_site id from YAML')),
            ],
        ),
        migrations.CreateModel(
            name='CanonSiteConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('residues', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('canon_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.canonsite')),
            ],
        ),
        migrations.CreateModel(
            name='QuatAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chains', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='cif_info',
            field=models.FileField(max_length=255, null=True, upload_to='target_loader_data/'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='compounds',
            field=models.ManyToManyField(to='viewer.Compound'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='event_map_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), null=True, size=None),
        ),
        migrations.AddField(
            model_name='experiment',
            name='mtz_info',
            field=models.FileField(max_length=255, null=True, upload_to='target_loader_data/'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pdb_info',
            field=models.FileField(max_length=255, null=True, upload_to='target_loader_data/'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pdb_sha256',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='type',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='version',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='xtalform',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xtalform',
            name='space_group',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xtalform',
            name='unit_cell_info',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='xtalform',
            name='xtalform_id',
            field=models.IntegerField(help_text='xtalform id from YAML', null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchi',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='compound',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='XtalformSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lig_chain', models.CharField(max_length=1)),
                ('residues', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('xtalform_site_id', models.IntegerField(help_text='xtalform site id from YAML')),
                ('canon_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.canonsite')),
                ('xtalform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.xtalform')),
            ],
        ),
        migrations.CreateModel(
            name='SiteOBservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('bound_file', models.FileField(max_length=255, null=True, upload_to='target_loader_data/')),
                ('apo_solv_file', models.FileField(max_length=255, null=True, upload_to='target_loader_data/')),
                ('apo_desolv_file', models.FileField(max_length=255, null=True, upload_to='target_loader_data/')),
                ('apo_file', models.FileField(max_length=255, null=True, upload_to='target_loader_data/')),
                ('xmap_2fofc_file', models.FileField(max_length=255, null=True, upload_to='target_loader_data/')),
                ('event_file', models.FileField(max_length=255, null=True, upload_to='target_loader_data/')),
                ('artefacts_file', models.FileField(max_length=255, null=True, upload_to='target_loader_data/')),
                ('trans_matrix_info', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('pdb_header_file', models.FileField(max_length=255, null=True, upload_to='target_loader_data/')),
                ('smiles', models.TextField()),
                ('seq_id', models.IntegerField()),
                ('chain_id', models.CharField(max_length=1)),
                ('ligand_mol_file', models.TextField()),
                ('canon_site_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.canonsiteconf')),
                ('cmpd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.compound')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.experiment')),
                ('xtalform_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.xtalformsite')),
            ],
        ),
        migrations.AddField(
            model_name='canonsiteconf',
            name='ref_site_observation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation'),
        ),
        migrations.AddField(
            model_name='canonsite',
            name='quat_assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.quatassembly'),
        ),
        migrations.AddField(
            model_name='canonsite',
            name='ref_conf_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viewer.canonsiteconf'),
        ),
        migrations.RemoveField(
            model_name='compound',
            name='long_inchi',
        ),
        migrations.AddField(
            model_name='xtalform',
            name='quat_assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.quatassembly'),
        ),
    ]
