# Generated by Django 3.1.14 on 2023-07-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0035_auto_20230705_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonsite',
            name='quat_assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.quatassembly'),
        ),
    ]
