# Generated by Django 3.1.14 on 2023-07-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0036_auto_20230709_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonsite',
            name='ref_conf_site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.canonsiteconf'),
        ),
    ]
