# Generated by Django 3.2.23 on 2024-02-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0037_rename_event_map_info_experiment_map_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='longcode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='longcode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xtalformsite',
            name='xtalform_site_num',
            field=models.IntegerField(
                help_text='numeric xtalform site id (enumerated on creation)', null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicalsiteobservation',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
