# Generated by Django 3.1.14 on 2023-07-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0037_auto_20230709_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonsiteconf',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
