# Generated by Django 3.1.14 on 2023-07-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0038_auto_20230709_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonsiteconf',
            name='ref_site_observation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation'),
        ),
    ]
