# Generated by Django 3.2.23 on 2024-02-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0039_canonsite_canon_site_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='quatassembly',
            name='assembly_num',
            field=models.IntegerField(
                help_text='numeric assembly id (enumerated on creation)', null=True
            ),
        ),
    ]
