# Generated by Django 3.2.20 on 2023-07-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0040_auto_20230709_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmolecule',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical molecule', 'verbose_name_plural': 'historical molecules'},
        ),
        migrations.AlterModelOptions(
            name='historicalsiteobservation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical site observation', 'verbose_name_plural': 'historical site observations'},
        ),
        migrations.RemoveField(
            model_name='historicalsiteobservation',
            name='trans_matrix_info',
        ),
        migrations.RemoveField(
            model_name='siteobservation',
            name='trans_matrix_info',
        ),
        migrations.AlterField(
            model_name='historicalmolecule',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsiteobservation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
