# Generated by Django 3.2.23 on 2024-02-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0040_quatassembly_assembly_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtalform',
            name='xtalform_num',
            field=models.IntegerField(
                help_text='numeric xtalform id (enumerated on creation)', null=True
            ),
        ),
    ]
