# Generated by Django 3.2.20 on 2023-08-16 12:08

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0041_auto_20230726_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteObservationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='The (unique) name of the tag', max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('colour', models.CharField(help_text='Expected to be an RGB string', max_length=20, null=True)),
                ('discourse_url', models.TextField(max_length=1000, null=True)),
                ('help_text', models.TextField(null=True)),
                ('additional_info', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Optional JSON field containing name/value pairs for future use', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='molecule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='molecule',
            name='cmpd_id',
        ),
        migrations.RemoveField(
            model_name='molecule',
            name='prot_id',
        ),
        migrations.AlterUniqueTogether(
            name='moleculetag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='moleculetag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='moleculetag',
            name='mol_group',
        ),
        migrations.RemoveField(
            model_name='moleculetag',
            name='molecules',
        ),
        migrations.RemoveField(
            model_name='moleculetag',
            name='target',
        ),
        migrations.RemoveField(
            model_name='moleculetag',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='protein',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='protein',
            name='aligned_to',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='computedmolecule',
            name='computed_inspirations',
        ),
        migrations.RemoveField(
            model_name='computedmolecule',
            name='pdb',
        ),
        migrations.AddField(
            model_name='computedmolecule',
            name='site_observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='viewer.siteobservation'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inspirations',
            field=models.ManyToManyField(blank=True, help_text='Foreign key link to any number of 3D Molecules that inspired the design of this compound', to='viewer.SiteObservation'),
        ),
        migrations.DeleteModel(
            name='HistoricalMolecule',
        ),
    ]
