# Generated by Django 3.2.20 on 2023-08-16 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_auto_20230816_1208'),
        ('hypothesis', '0004_auto_20230816_1208'),
        ('viewer', '0042_auto_20230816_1208'),
        ('hotspots', '0003_auto_20230816_1208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Molecule',
        ),
        migrations.DeleteModel(
            name='MoleculeTag',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
        migrations.AddField(
            model_name='siteobservationtag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.tagcategory'),
        ),
        migrations.AddField(
            model_name='siteobservationtag',
            name='mol_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.siteobservationgroup'),
        ),
        migrations.AddField(
            model_name='siteobservationtag',
            name='site_observations',
            field=models.ManyToManyField(blank=True, to='viewer.SiteObservation'),
        ),
        migrations.AddField(
            model_name='siteobservationtag',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.target'),
        ),
        migrations.AddField(
            model_name='siteobservationtag',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='siteobservationtag',
            unique_together={('tag', 'target')},
        ),
    ]
