# Generated by Django 3.2.23 on 2024-02-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0044_computedmolecule_pdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedmolecule',
            name='pdb_info',
            field=models.FileField(
                help_text='Link to pdb file; user-uploaded pdb or pdb.experiment.pdb_info',
                max_length=255,
                null=True,
                upload_to='computed_set_data/',
            ),
        ),
        migrations.AlterField(
            model_name='computedmolecule',
            name='pdb',
            field=models.ForeignKey(
                help_text='SiteObservation object user referenced in upload (if given)',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='pdb',
                to='viewer.siteobservation',
            ),
        ),
    ]
