# Generated by Django 3.2.20 on 2023-08-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0045_auto_20230818_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='inspirations',
            field=models.ManyToManyField(blank=True, help_text='Foreign key link to any number of 3D Molecules that inspired the design of this compound', to='viewer.SiteObservation'),
        ),
        migrations.AlterField(
            model_name='siteobservationtag',
            name='site_observations',
            field=models.ManyToManyField(blank=True, to='viewer.SiteObservation'),
        ),
    ]
