# Generated by Django 3.2.23 on 2024-02-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0045_auto_20240221_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprojecttag',
            name='upload_name',
            field=models.CharField(
                default='', help_text='The generated name of the tag', max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteobservationtag',
            name='upload_name',
            field=models.CharField(
                default='default',
                help_text='The generated name of the tag',
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sessionprojecttag',
            unique_together={('upload_name', 'target')},
        ),
        migrations.AlterUniqueTogether(
            name='siteobservationtag',
            unique_together={('upload_name', 'target')},
        ),
    ]
