# Generated by Django 3.2.23 on 2024-03-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0046_auto_20240228_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='ligand_pdb',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='ligand_pdb',
            field=models.FileField(
                max_length=255, null=True, upload_to='target_loader_data/'
            ),
        ),
    ]
