# Generated by Django 3.2.23 on 2024-03-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0047_auto_20240301_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprojecttag',
            name='tag_prefix',
            field=models.TextField(
                help_text='Tag prefix for auto-generated tags', null=True
            ),
        ),
        migrations.AddField(
            model_name='siteobservationtag',
            name='tag_prefix',
            field=models.TextField(
                help_text='Tag prefix for auto-generated tags', null=True
            ),
        ),
    ]
