# Generated by Django 3.2.23 on 2024-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0048_auto_20240305_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='ligand_mol',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='ligand_smiles',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='ligand_mol',
            field=models.FileField(
                max_length=255, null=True, upload_to='target_loader_data/'
            ),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='ligand_smiles',
            field=models.FileField(
                max_length=255, null=True, upload_to='target_loader_data/'
            ),
        ),
    ]
