# Generated by Django 3.2.24 on 2024-04-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0049_auto_20240307_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pose',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('display_name', models.TextField(null=True)),
                (
                    'canon_site',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.canonsite',
                    ),
                ),
                (
                    'compound',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.compound',
                    ),
                ),
                (
                    'main_site_observation',
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='main_pose',
                        to='viewer.siteobservation',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='pose',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='viewer.pose',
            ),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='pose',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.pose'
            ),
        ),
    ]
