# Generated by Django 3.2.24 on 2024-04-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0049_auto_20240307_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprojecttag',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteobservationtag',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
