# Generated by Django 3.2.24 on 2024-05-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0051_auto_20240425_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonsite',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canonsiteconf',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xtalformsite',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
    ]
