# Generated by Django 3.2.24 on 2024-05-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0051_alter_siteobservation_pose'),
        ('viewer', '0053_auto_20240503_1302'),
    ]

    operations = [
    ]
