# Generated by Django 3.2.25 on 2024-05-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0054_auto_20240509_0838'),
        ('viewer', '0054_merge_20240507_1558'),
    ]

    operations = [
    ]
