# Generated by Django 3.2.25 on 2024-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0055_merge_20240516_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='inchi_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
