# Generated by Django 3.2.25 on 2024-06-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0056_compound_inchi_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedmolecule',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchi_key',
            field=models.CharField(blank=True, db_index=True, max_length=27),
        ),
    ]
