# Generated by Django 3.2.25 on 2024-07-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0058_auto_20240614_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computedmolecule',
            name='version',
        ),
    ]
