# Generated by Django 3.2.25 on 2024-07-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0059_remove_computedmolecule_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonsite',
            name='centroid_res',
            field=models.TextField(null=True),
        ),
    ]
