# Generated by Django 3.2.25 on 2024-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0060_canonsite_centroid_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprojecttag',
            name='short_tag',
            field=models.TextField(help_text='The generated shorter version of tag (without target name)', null=True),
        ),
        migrations.AddField(
            model_name='siteobservationtag',
            name='short_tag',
            field=models.TextField(help_text='The generated shorter version of tag (without target name)', null=True),
        ),
        migrations.AlterField(
            model_name='sessionprojecttag',
            name='upload_name',
            field=models.CharField(help_text='The generated long name of the tag', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteobservationtag',
            name='upload_name',
            field=models.CharField(help_text='The generated long name of the tag', max_length=200),
        ),
    ]
