# Generated by Django 3.2.25 on 2024-09-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0060_canonsite_centroid_res'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsiteobservation',
            name='ligand_mol_file',
        ),
        migrations.RemoveField(
            model_name='siteobservation',
            name='ligand_mol_file',
        ),
    ]
