# Generated by Django 3.2.25 on 2024-09-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0061_auto_20240905_0756'),
        ('viewer', '0062_experiment_code_prefix'),
    ]

    operations = [
    ]
