# Generated by Django 3.2.25 on 2024-09-18 12:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0063_merge_20240906_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='cif_info_source_file',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='map_info_source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='experiment',
            name='mtz_info_source_file',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pdb_info_source_file',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='pose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_observations', to='viewer.pose'),
        ),
    ]
