# Generated by Django 3.2.25 on 2024-10-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0064_auto_20240918_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='ligand_name',
            field=models.TextField(blank=True, default='LIG'),
        ),
    ]
