# Generated by Django 3.2.25 on 2024-09-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0064_auto_20240918_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='project_rename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_rename', to='viewer.project'),
        ),
        migrations.AlterField(
            model_name='target',
            name='title',
            field=models.CharField(help_text='A title, i.e. Mpro', max_length=200),
        ),
    ]
