# Generated by Django 3.2.25 on 2024-09-19 15:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0065_auto_20240919_1502'),
    ]

    def restruct_projects(apps, schema_editor):
        Target = apps.get_model('viewer', 'Target')

        # atm, target has m2m to project
        # added foreign key to project to target model
        # go through projects and set the correct key

        # NB! this schema allows target to be in multiple
        # projects. with new schema this is not possible

        for target in Target.objects.all():
            projects = target.project_id.all()
            if projects.count() > 1:
                # this shouldn't exist, but if it for some reason
                # does, make some noise
                raise ValueError(
                    f'Target id={target.pk} is under multiple projects!'
                    + ' Resolve conflict before re-running migration.',
                )
            else:
                target.project_rename = projects[0]
                target.save()



    # This is unlikely to be possible and even less likely ever required
    def destruct_projects(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(restruct_projects, destruct_projects)
    ]
