# Generated by Django 3.2.25 on 2024-09-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0066_auto_20240919_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='project_id',
        ),
    ]
