# Generated by Django 3.2.25 on 2024-09-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0067_remove_target_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='project_rename',
            new_name='project',
        ),
    ]
