# Generated by Django 3.2.25 on 2024-09-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0068_rename_project_rename_target_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.project'),
        ),
    ]
