# Generated by Django 3.2.25 on 2024-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0070_alter_target_project'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(fields=('title', 'project'), name='unique_target_in_project'),
        ),
    ]
