# Generated by Django 3.2.25 on 2024-10-10 14:37

from pathlib import Path

from django.db import migrations

from fragalysis.settings import MEDIA_ROOT, TARGET_LOADER_MEDIA_DIRECTORY

from viewer.utils import sanitize_directory_name


# continuation of the data migration to replace m2m between target and
# project with fk in target to project
# starts in 0066, where target gets the fk to project populated
# migrations in between take care of changing the schema
# this one now moves the data to correct locations

class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0071_target_unique_target_in_project'),
    ]


    def move_data(apps, schema_editor):
        Target = apps.get_model('viewer', 'Target')
        root_path = Path(MEDIA_ROOT).joinpath(TARGET_LOADER_MEDIA_DIRECTORY)
        for target in Target.objects.all():
            new_archive_dir = sanitize_directory_name(
                f"{target.zip_archive}_{target.project.title}",
                root_path,
            )
            old_data_path = root_path.joinpath(target.zip_archive)
            new_data_path = root_path.joinpath(new_archive_dir)

            old_data_path.rename(new_data_path)

            # move tarballs
            for exp_upload in target.experimentupload_set.all():
                tarball_path = root_path.joinpath(exp_upload.file.name)
                new_tarball_path = new_data_path.joinpath(exp_upload.file.name)
                tarball_path.rename(new_tarball_path)

            target.zip_archive = new_archive_dir
            target.save()


    def unmove_data(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(move_data, unmove_data)
    ]
