# Generated by Django 3.2.25 on 2024-10-10 14:37

from pathlib import Path

from django.db import migrations

from fragalysis.settings import MEDIA_ROOT, TARGET_LOADER_MEDIA_DIRECTORY

from viewer.models import ComputedMolecule
from viewer.utils import sanitize_directory_name


# continuation of the data migration to replace m2m between target and
# project with fk in target to project
# starts in 0066, where target gets the fk to project populated
# migrations in between take care of changing the schema
# this one now moves the data to correct locations

class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0071_target_unique_target_in_project'),
    ]


    def move_data(apps, schema_editor):
        Target = apps.get_model('viewer', 'Target')
        root_path = Path(MEDIA_ROOT).joinpath(TARGET_LOADER_MEDIA_DIRECTORY)
        for target in Target.objects.all():


            if target.zip_archive:
                if target.zip_archive.name.endswith(target.project.title):
                    # probably already processed. due to resource path
                    # glitch, this migration was applied twice in prod
                    continue

                old_data_path = root_path.joinpath(target.zip_archive.name)
                new_archive_dir = sanitize_directory_name(
                    f"{target.zip_archive.name}_{target.project.title}",
                    root_path,
                )
                new_data_path = root_path.joinpath(new_archive_dir)
                if not new_data_path.exists():
                    old_data_path.rename(new_data_path)
                # move tarballs
                for exp_upload in target.experimentupload_set.all():
                    tarball_path = root_path.joinpath(exp_upload.file.name)
                    if tarball_path.exists():
                        new_tarball_path = new_data_path.joinpath(exp_upload.file.name)
                        tarball_path.rename(new_tarball_path)
                    else:
                        # some tarballs really do not exist on prod!
                        print(f'Tarball {tarball_path.name} does not exist')
            else:
                # old system, data path contains task_id
                new_archive_dir = sanitize_directory_name(
                    f"{target.title}_{target.project.title}",
                    root_path,
                )
                new_data_path = root_path.joinpath(new_archive_dir)
                new_data_path.mkdir(parents=True, exist_ok=False)
                for exp_upload in target.experimentupload_set.all():
                    old_data_path = root_path.joinpath(str(exp_upload.task_id))
                    # can only be one
                    target_subdir = [p for p in old_data_path.glob("*") if p.is_dir()][0]
                    target_tarball = [p for p in old_data_path.glob("*") if p.is_file()][0]

                    upload_dir = next(target_subdir.glob('upload_*'))
                    # NB! move tarball first!
                    new_tarball_path = new_data_path.joinpath(target_tarball.name)
                    target_tarball.rename(new_tarball_path)
                    # and then the rest of the data
                    upload_dir.rename(new_data_path.joinpath(upload_dir.parts[-1]))



            target.zip_archive = new_archive_dir
            target.save()


    def unmove_data(apps, schema_editor):
        pass

    @staticmethod
    def update_path(value, target_dir):
        if value:
            path = Path(str(value))
            parts = list(path.parts)
            if len(parts) > 2 and parts[1] != target_dir:
                parts[1] = target_dir
                value = str(Path(*parts))

        return value


    @staticmethod
    def update_field(instance, field, target_dir):
        value = getattr(instance, field, None)
        path = Migration.update_path(value, target_dir)
        setattr(instance, field, path)

        return instance


    def update_file_names(apps, schema_editor):
        # this is delibarately skipping historical models
        ExperimentUpload = apps.get_model('viewer', 'ExperimentUpload')
        Experiment = apps.get_model('viewer', 'Experiment')
        SiteObservation = apps.get_model('viewer', 'SiteObservation')
        ComputedMolecule = apps.get_model('viewer', 'ComputedMolecule')

        experiment_upload_fields = (
            'neighbourhood_transforms',
            'conformer_site_transforms',
            'reference_structure_transforms',
        )

        experiment_fields = (
            'pdb_info',
            'pdb_info_source_file',
            'mtz_info',
            'mtz_info_source_file',
            'cif_info',
            'cif_info_source_file',
        )

        experiment_arr_fields = 'map_info_source_files'

        site_observation_fields = (
            'bound_file',
            'apo_solv_file',
            'apo_desolv_file',
            'apo_file',
            'sigmaa_file',
            'diff_file',
            'event_file',
            'artefacts_file',
            'pdb_header_file',
            'ligand_mol',
            'ligand_smiles',
            'ligand_pdb',
        )

        for instance in ExperimentUpload.objects.all():
            target_dir = instance.target.zip_archive.name
            for field in experiment_upload_fields:
                instance = Migration.update_field(instance, field, target_dir)

            instance.save()

        for instance in Experiment.objects.all():
            target_dir = instance.experiment_upload.target.zip_archive.name
            for field in experiment_fields:
                instance = Migration.update_field(instance, field, target_dir)

            value = getattr(instance, experiment_arr_fields, None)
            if value:
                paths = [Migration.update_path(v, target_dir) for v in value]
                setattr(instance, experiment_arr_fields, paths)


            instance.save()

        for instance in SiteObservation.objects.all():
            target_dir = instance.experiment.experiment_upload.target.zip_archive.name
            for field in site_observation_fields:
                instance = Migration.update_field(instance, field, target_dir)

            instance.save()

        for instance in ComputedMolecule.objects.all():
            target_dir = instance.computed_set.all()[0].target.zip_archive.name
            for field in site_observation_fields:
                instance = Migration.update_field(instance, field, target_dir)

            instance.save()


    def reverse_update_file_names(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(move_data, unmove_data),
        migrations.RunPython(update_file_names, reverse_update_file_names),
    ]
