# Generated by Django 3.2.25 on 2024-10-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0065_compound_ligand_name'),
        ('viewer', '0072_auto_20241010_1437'),
    ]

    operations = [
    ]
