# Generated by Django 3.2.25 on 2024-11-04 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0072_auto_20241010_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalComputedSet',
            fields=[
                ('name', models.CharField(db_index=True, max_length=50)),
                ('submitted_sdf', models.TextField(help_text='The original SDF containing the ComputedSet', max_length=255)),
                ('written_sdf_filename', models.TextField(help_text='The written ComputedSet filename', max_length=1000, null=True)),
                ('spec_version', models.FloatField(help_text='The version of the SDF file format specification')),
                ('method_url', models.TextField(help_text='A url linking to a write-up of the methodology used to create the computed set', max_length=1000, null=True)),
                ('method', models.CharField(blank=True, help_text='The name of the algorithmic method used to generate the compounds (e.g. Fragmenstein)', max_length=50, null=True)),
                ('upload_date', models.DateField(blank=True, help_text='The date the set was uploaded', null=True)),
                ('md_ordinal', models.SmallIntegerField(blank=True, help_text='The ordinal distinguishing between uploads using the same method and date', null=True)),
                ('upload_task_id', models.CharField(help_text='The task ID of the upload Celery task', max_length=50, null=True)),
                ('upload_status', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED')], help_text='Status of the upload. Only be updated at the end of the process', max_length=7, null=True)),
                ('upload_progress', models.DecimalField(decimal_places=2, help_text='Intended to be used as an indication of progress (0 to 100%)', max_digits=5, null=True)),
                ('upload_datetime', models.DateTimeField(help_text='The datetime the upload was completed', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viewer.computedsetsubmitter')),
                ('target', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viewer.target')),
            ],
            options={
                'verbose_name': 'historical computed set',
                'verbose_name_plural': 'historical computed sets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
