# Generated by Django 3.2.25 on 2024-10-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0073_merge_20241018_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoundidentifiertype',
            name='id',
        ),
        migrations.AlterField(
            model_name='compoundidentifier',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='compoundidentifiertype',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
