# Generated by Django 3.2.25 on 2024-10-18 10:28

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0073_merge_20241018_0956'),
    ]

    def fk_to_new_type(apps, schema_editor):
        CompoundIdentifier = apps.get_model('viewer', 'CompoundIdentifier')

        for idf in CompoundIdentifier.objects.all():
            idf.name_type = idf.type.name
            idf.save()

    def reverse_fk_to_new_type(apps, schema_editor):
        pass

    # with my edits:
    operations = [
        migrations.RunPython(lambda apps, schema_editor: print('first migration')),
        migrations.AlterField(
            model_name='compoundidentifiertype',
            name='name',
            field=models.TextField(unique=True),
        ),
        # add new foreign key field to CompoundIdentifier
        migrations.RunPython(lambda apps, schema_editor: print('second migration')),
        migrations.AddField(
            model_name='compoundidentifier',
            name='name_type',
            field=models.ForeignKey(null=True, to_field='name', on_delete=django.db.models.deletion.CASCADE, to='viewer.compoundidentifiertype'),
        ),
        # populate values in new field
        migrations.RunPython(lambda apps, schema_editor: print('third migration, data')),
        migrations.RunPython(fk_to_new_type, reverse_fk_to_new_type),

        # continue with the original migration, remove field, set the new pk
        migrations.RunPython(lambda apps, schema_editor: print('fourth migration')),
        migrations.RemoveField(
            model_name='compoundidentifiertype',
            name='id',
        ),
        # migrations.AlterField(
        #     model_name='compoundidentifier',
        #     name='name',
        #     field=models.TextField(),
        # ),
        migrations.RunPython(lambda apps, schema_editor: print('last migration')),
        migrations.AlterField(
            model_name='compoundidentifiertype',
            name='name',
            field=models.TextField(primary_key=True, unique=True, serialize=False),
        ),
    ]
