# Generated by Django 3.2.25 on 2024-10-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0073_merge_20241028_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='modeled_smiles_canon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='modeled_smiles_soakdb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='soaked_smiles_canon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='soaked_smiles_soakdb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
