# Generated by Django 3.2.25 on 2024-10-18 10:28

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0073_merge_20241018_0956'),
    ]

    def temporary_name(apps, schema_editor):
        CompoundIdentifier = apps.get_model('viewer', 'CompoundIdentifier')

        for idf in CompoundIdentifier.objects.all():
            idf.name_type = idf.type.name
            idf.save()

    def reverse_temporary_name(apps, schema_editor):
        pass


    # this contains some edits, the automatically constructed
    # migration was not in the correct order, so I had to move things
    # around to preserve data
    operations = [
        migrations.AddField(
            model_name='compoundidentifier',
            name='name_type',
            field=models.TextField(null=True),
        ),
        migrations.RunPython(temporary_name, reverse_temporary_name),
        migrations.RemoveField(
            model_name='compoundidentifier',
            name='type',
        ),
        migrations.RemoveField(
            model_name='compoundidentifiertype',
            name='id',
        ),
        migrations.AlterField(
            model_name='compoundidentifiertype',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
