# Generated by Django 3.2.25 on 2024-10-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0074_auto_20241018_1028'),
    ]

    def relink_type(apps, schema_editor):
        CompoundIdentifier = apps.get_model('viewer', 'CompoundIdentifier')
        CompoundIdentifierType = apps.get_model('viewer', 'CompoundIdentifierType')

        for idf in CompoundIdentifier.objects.all():
            idf.type = CompoundIdentifierType.objects.get(name=idf.name_type)
            idf.save()

    def reverse_relink_type(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(lambda apps, schema_editor: print('migration 0075')),
        # migrations.RemoveField(
        #     model_name='compoundidentifier',
        #     name='type',
        # ),
        migrations.AddField(
            model_name='compoundidentifier',
            name='type',
            field=models.ForeignKey(null=True, to_field='name', on_delete=django.db.models.deletion.CASCADE, to='viewer.compoundidentifiertype'),
        ),
        migrations.RunPython(relink_type, reverse_relink_type),
    ]
