# Generated by Django 3.2.25 on 2024-10-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0076_compoundidentifier_type'),
    ]

    operations = [
        migrations.RunPython(lambda apps, schema_editor: print('migration 0077')),
        migrations.AlterField(
            model_name='compoundidentifier',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.compoundidentifiertype'),
        ),
    ]
