# Generated by Django 3.2.25 on 2024-10-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0077_alter_compoundidentifier_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compoundidentifier',
            constraint=models.UniqueConstraint(fields=('type', 'compound', 'name'), name='unique_compoundidentifier'),
        ),
    ]
