# Generated by Django 3.2.25 on 2024-10-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0078_compoundidentifier_unique_compoundidentifier'),
    ]


    def move_contents(apps, schema_editor):
        Compound = apps.get_model('viewer', 'Compound')

        for compound in Compound.objects.all():
            compound.description = compound.current_identifier
            compound.save()

    def reverse_move_contents(apps, schema_editor):
        pass



    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='all_identifiers',
        ),

        migrations.RunPython(move_contents, reverse_move_contents),
        migrations.RemoveField(
            model_name='compound',
            name='current_identifier',
        ),
        migrations.AddField(
            model_name='compound',
            name='current_identifier',
            field=models.ForeignKey(blank=True, help_text='The preferred alias for this compound.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viewer.compoundidentifier'),
        ),
    ]
