# Generated by Django 3.2.25 on 2024-10-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0079_auto_20241023_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundidentifier',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_identifiers', to='viewer.compound'),
        ),
    ]
