# Generated by Django 3.2.25 on 2024-10-23 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0080_alter_compoundidentifier_compound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='current_identifier',
            field=models.OneToOneField(blank=True, help_text='The preferred alias for this compound.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viewer.compoundidentifier'),
        ),
    ]
