# Generated by Django 3.2.25 on 2024-11-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0074_auto_20241028_1617'),
        ('viewer', '0081_alter_compound_current_identifier'),
    ]

    operations = [
    ]
