# Generated by Django 3.2.25 on 2024-11-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0073_historicalcomputedset'),
        ('viewer', '0082_merge_20241105_1058'),
    ]

    operations = [
    ]
