# Generated by Django 3.2.25 on 2024-11-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0083_merge_20241105_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='ligand_sdf',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='ligand_sdf',
            field=models.FileField(max_length=255, null=True, upload_to='target_loader_data/'),
        ),
        migrations.AlterField(
            model_name='compoundidentifier',
            name='name',
            field=models.TextField(),
        ),
    ]
