# Generated by Django 3.2.25 on 2024-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0084_auto_20241108_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computedset',
            name='computed_molecules',
        ),
        migrations.AlterField(
            model_name='computedsetcomputedmolecule',
            name='computed_set',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='computed_set',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scoredescription',
            name='computed_set',
            field=models.TextField(null=True),
        ),
    ]
