# Generated by Django 3.2.25 on 2024-12-04 16:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0084_auto_20241108_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='alias_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
