# Generated by Django 3.2.25 on 2024-12-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0085_target_alias_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentupload',
            name='data_version_major',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experimentupload',
            name='data_version_minor',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
