# Generated by Django 3.2.25 on 2024-12-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0085_auto_20241202_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedset',
            name='new_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcomputedset',
            name='new_id',
            field=models.IntegerField(default=0),
        ),
    ]
