# Generated by Django 3.2.25 on 2025-01-30 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0086_auto_20241213_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityStatusType',
            fields=[
                ('status', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteObservationQualityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('auto_assigned', models.BooleanField(default=False)),
                ('main_status', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('site_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.qualitystatustype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
    ]
