# Generated by Django 3.2.25 on 2024-12-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0086_auto_20241202_1205'),
    ]

    def populate_ids(apps, schema_editor):
        ComputedSet = apps.get_model('viewer', 'ComputedSet')

        for i, obj in enumerate(ComputedSet.objects.all()):
            obj.new_id = i + 1
            obj.save()

    def reverse_populate_ids(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(populate_ids, reverse_populate_ids),
    ]
