# Generated by Django 3.2.25 on 2025-01-30 15:55

from django.db import migrations


statuses = (
    'GOOD',
    'MEDIOCRE',
    'BAD',
    'NONE',
)

class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0087_qualitystatustype_siteobservationqualitystatus'),
    ]

    def add_quality_status_types(apps, schema_editor):
        QualityStatusType = apps.get_model("viewer", "QualityStatusType")

        for status in statuses:
            QualityStatusType(status=status).save()



    def remove_quality_status_types(apps, schema_editor):
        QualityStatusType = apps.get_model("viewer", "QualityStatusType")
        SiteObservationQualityStatus = apps.get_model("viewer", "SiteObservationQualityStatus")
        SiteObservationQualityStatus.objects.all().delete()
        QualityStatusType.objects.all().delete()


    operations = [
        migrations.RunPython(add_quality_status_types, remove_quality_status_types)
    ]
