# Generated by Django 3.2.25 on 2024-12-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0087_auto_20241202_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedset',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='new_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcomputedset',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalcomputedset',
            name='new_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
