# Generated by Django 3.2.25 on 2024-12-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0088_auto_20241202_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computedset',
            old_name='new_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historicalcomputedset',
            old_name='new_id',
            new_name='id',
        ),
    ]
