# Generated by Django 3.2.25 on 2024-12-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0090_auto_20241202_1231'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='computedsetcomputedmolecule',
            name='unique_computedsetcomputedmolecule',
        ),
        migrations.RenameField(
            model_name='computedsetcomputedmolecule',
            old_name='computed_set',
            new_name='computed_set_txt',
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='computed_set',
            new_name='computed_set_txt',
        ),
        migrations.RenameField(
            model_name='scoredescription',
            old_name='computed_set',
            new_name='computed_set_txt',
        ),
    ]
