# Generated by Django 3.2.25 on 2024-12-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0091_auto_20241202_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedsetcomputedmolecule',
            name='computed_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.computedset'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='computed_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.computedset'),
        ),
        migrations.AddField(
            model_name='scoredescription',
            name='computed_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.computedset'),
        ),
    ]
