# Generated by Django 3.2.25 on 2024-12-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0092_auto_20241202_1322'),
    ]

    def populate_fks(apps, schema_editor):
        ComputedSet = apps.get_model('viewer', 'ComputedSet')
        ComputedSetComputedMolecule = apps.get_model('viewer', 'ComputedSetComputedMolecule')
        ScoreDescription = apps.get_model('viewer', 'ScoreDescription')
        JobRequest = apps.get_model('viewer', 'JobRequest')

        for model in (ComputedSetComputedMolecule, ScoreDescription, JobRequest):
            for obj in model.objects.all():
                obj.computed_set = ComputedSet.objects.get(name=obj.computed_set_txt)
                obj.save()

    def reverse_populate_fks(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(populate_fks, reverse_populate_fks),
    ]
