# Generated by Django 3.2.25 on 2024-12-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0093_auto_20241202_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computedsetcomputedmolecule',
            name='computed_set_txt',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='computed_set_txt',
        ),
        migrations.RemoveField(
            model_name='scoredescription',
            name='computed_set_txt',
        ),
        migrations.AlterField(
            model_name='computedsetcomputedmolecule',
            name='computed_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.computedset'),
        ),
    ]
