# Generated by Django 3.2.25 on 2024-12-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0094_auto_20241202_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedset',
            name='computed_molecules',
            field=models.ManyToManyField(related_name='computed_set', through='viewer.ComputedSetComputedMolecule', to='viewer.ComputedMolecule'),
        ),
        migrations.AddConstraint(
            model_name='computedsetcomputedmolecule',
            constraint=models.UniqueConstraint(fields=('computed_set', 'computed_molecule'), name='unique_computedsetcomputedmolecule'),
        ),
    ]
