# Generated by Django 3.2.25 on 2024-12-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0095_auto_20241202_1336'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='computedset',
            constraint=models.UniqueConstraint(fields=('name', 'target'), name='unique_computedsetname_target'),
        ),
    ]
