# Generated by Django 3.2.25 on 2024-12-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0085_target_alias_order'),
        ('viewer', '0096_computedset_unique_computedsetname_target'),
    ]

    operations = [
    ]
