# Generated by Django 3.2.25 on 2025-02-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0086_auto_20241213_1042'),
        ('viewer', '0097_merge_20241212_1048'),
    ]

    operations = [
    ]
