# Generated by Django 3.2.25 on 2025-02-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0088_auto_20250130_1555'),
        ('viewer', '0098_merge_20250204_1324'),
    ]

    operations = [
    ]
