# Generated by Django 3.2.25 on 2025-02-13 10:39

from django.db import migrations
from django.db.models import Count


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0099_merge_20250205_0819'),
    ]

    def fix_supersedes(apps, schema_editor):
        SiteObservation = apps.get_model("viewer", "SiteObservation")
        obvs_groups = SiteObservation.objects.values(
            'experiment_id',
            'code',
        ).annotate(
            obvs_count=Count('code'),
        ).filter(obvs_count__gt=1)

        for obvs_group in obvs_groups:
            qs = SiteObservation.objects.filter(
                experiment_id=obvs_group['experiment_id'],
                code=obvs_group['code'],
            ).order_by('-version')
            for obvs in qs[1:]:
                obvs.superseded = True
                obvs.save()


    def unfix_supersedes(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(fix_supersedes, unfix_supersedes)
    ]
