# Generated by Django 3.2.25 on 2025-02-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0100_auto_20250213_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefinementStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('default_quality_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.qualitystatustype')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='refinement_outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.refinementstatustype'),
        ),
        migrations.AddConstraint(
            model_name='refinementstatustype',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_refinement_code'),
        ),
    ]
