# Generated by Django 3.2.25 on 2025-02-26 11:46

from django.db import migrations


# contents moved to 0106, forgot to save here..

class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0101_auto_20250226_1139'),
    ]


    operations = [
    ]
