# Generated by Django 3.2.25 on 2025-02-26 11:46

from django.db import migrations



refinement_status = (
    (0, "All Datasets"),
    (1, "Analysis Pending"),
    (2, "PANDDA model"),
    (3, "In Refinement"),
    (4, "CompChem Ready"),
    (5, "Deposition Ready"),
    (6, "Deposited"),
    (7, "Analysed & Rejected"),
)

class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0101_auto_20250226_1139'),
    ]

    def populate_refinements(apps, schema_editor):
        RefinementStatusType = apps.get_model("viewer", "RefinementStatusType")
        for code, description in refinement_status:
            RefinementStatusType(
                code=code,
                description=description,
            )



    def depopulate_refinements(apps, schema_editor):
        RefinementStatusType = apps.get_model("viewer", "RefinementStatusType")
        RefinementStatusType.objects.all().delete()


    operations = [
        migrations.RunPython(populate_refinements, depopulate_refinements)
    ]
