# Generated by Django 3.2.25 on 2025-02-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0102_auto_20250226_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refinementstatustype',
            name='default_quality_status',
        ),
    ]
