# Generated by Django 3.2.25 on 2025-02-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0103_remove_refinementstatustype_default_quality_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='siteobservationqualitystatus',
            constraint=models.UniqueConstraint(condition=models.Q(('main_status', True)), fields=('site_observation',), name='unique_main_status_per_site_observation'),
        ),
    ]
