# Generated by Django 3.2.25 on 2025-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0104_siteobservationqualitystatus_unique_main_status_per_site_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(null=True)),
            ],

        ),
        migrations.AddConstraint(
            model_name='experimentstatustype',
            constraint=models.UniqueConstraint(fields=('status_code',), name='unique_experiment_status'),
        ),
    ]
