# Generated by Django 3.2.25 on 2025-03-18 15:23

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0104_siteobservationqualitystatus_unique_main_status_per_site_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='external_url_display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='long_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='organism',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='settings',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='short_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
