# Generated by Django 3.2.25 on 2025-03-12 13:19

from django.db import migrations


experiment_status = (
    (0, "new"),
    (1, "deprecated"),
    (2, "superseded"),
    (3, "unchanged"),
    (4, "newer_data_exists"),
)

refinement_status = (
    (0, "All Datasets"),
    (1, "Analysis Pending"),
    (2, "PANDDA model"),
    (3, "In Refinement"),
    (4, "CompChem Ready"),
    (5, "Deposition Ready"),
    (6, "Deposited"),
    (7, "Analysed & Rejected"),
)

class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0105_auto_20250312_1318'),
    ]

    def populate_status(apps, schema_editor):
        ExperimentStatusType = apps.get_model("viewer", "ExperimentStatusType")
        for code, description in experiment_status:
            ExperimentStatusType(
                status_code=code,
                status=description,
            ).save()



    def depopulate_status(apps, schema_editor):
        ExperimentStatusType = apps.get_model("viewer", "ExperimentStatusType")
        ExperimentStatusType.objects.all().delete()


    def populate_old_status(apps, schema_editor):
        Experiment = apps.get_model("viewer", "Experiment")
        for exp in Experiment.objects.all():
            exp.status_old = exp.status
            exp.save()


    def populate_refinements(apps, schema_editor):
        RefinementStatusType = apps.get_model("viewer", "RefinementStatusType")
        for code, description in refinement_status:
            RefinementStatusType(
                code=code,
                description=description,
            ).save()



    def depopulate_refinements(apps, schema_editor):
        RefinementStatusType = apps.get_model("viewer", "RefinementStatusType")
        RefinementStatusType.objects.all().delete()


    operations = [
        migrations.RunPython(populate_status, depopulate_status),
        migrations.RunPython(populate_refinements, depopulate_refinements),
    ]
