# Generated by Django 3.2.25 on 2025-03-12 13:19

from django.db import migrations


experiment_status = (
    (0, "new"),
    (1, "deprecated"),
    (2, "superseded"),
    (3, "unchanged"),
    (4, "excluded"),
)

class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0105_auto_20250312_1318'),
    ]

    def populate_status(apps, schema_editor):
        ExperimentStatusType = apps.get_model("viewer", "ExperimentStatusType")
        for code, description in experiment_status:
            ExperimentStatusType(
                status_code=code,
                status=description,
            )



    def depopulate_status(apps, schema_editor):
        ExperimentStatusType = apps.get_model("viewer", "ExperimentStatusType")
        ExperimentStatusType.objects.all().delete()


    def populate_old_status(apps, schema_editor):
        Experiment = apps.get_model("viewer", "Experiment")
        for exp in Experiment.objects.all():
            exp.status_old = exp.status
            exp.save()


    operations = [
        migrations.RunPython(populate_status, depopulate_status),
    ]
