# Generated by Django 3.2.25 on 2025-03-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0105_auto_20250318_1523'),
        ('viewer', '0107_alter_experiment_status'),
    ]

    operations = [
    ]
