# Generated by Django 3.2.25 on 2025-03-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0108_merge_20250319_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedsetsubmitter',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='computedsetsubmitter',
            name='institution',
            field=models.TextField(help_text='The institution or organizational affiliation of the compound set submitter'),
        ),
        migrations.AlterField(
            model_name='computedsetsubmitter',
            name='method',
            field=models.TextField(help_text='A name for the method that was used to produce the uploaded data'),
        ),
        migrations.AlterField(
            model_name='computedsetsubmitter',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='computedsetsubmitter',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='computedsetsubmitter',
            constraint=models.UniqueConstraint(fields=('email', 'method'), name='unique_computedsetsubmitter_email_method'),
        ),
    ]
