# Generated by Django 3.2.25 on 2025-03-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0109_auto_20250325_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedsetsubmitter',
            name='generation_date',
            field=models.DateField(null=True),
        ),
    ]
