# Generated by Django 3.2.25 on 2025-04-10 16:29

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0110_alter_computedsetsubmitter_generation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='cchalf_high_res_shell',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='cchalf_overall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='completeness_high_res_shell',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='completeness_overall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='crystal_mounting_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='data_collection_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='data_collection_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='date_model_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='date_status_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='dimple_rfree',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='dimple_rwork',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='final_compound_concentration_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='high_resolution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='isig_i_high_res_shell',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='isig_i_overall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='library',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='library_plate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='ligand_confidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='ligand_correlation_coefficient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='model_last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment',
            name='modelled_smiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='panddarun',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pdb_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='processing_pipeline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='refined_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment',
            name='refinement_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='refinement_rfree',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='refinement_rwork',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='soakdb_entry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='soaking_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='source_well',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='space_group',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='unit_cell_dimensions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
    ]
