# Generated by Django 3.2.25 on 2025-05-13 12:16

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0112_experiment_date_refined'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='state',
            field=models.JSONField(default=0, encoder=django.core.serializers.json.DjangoJSONEncoder),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SnapshotScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.TextField(null=True)),
                ('screenshot_type', models.IntegerField(null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.snapshot')),
            ],
        ),
    ]
