# Generated by Django 3.2.25 on 2025-04-30 10:08

from django.db import migrations


data_type = (
    ("text", "text"),
    ("float", "double precision"),
    ("integer", "signed four-byte integer"),
)

modifier = (
    (">", "gt"),
    (">=", "gte"),
    ("<", "lt"),
    ("=<", "lte"),
)

class Migration(migrations.Migration):

    def populate_modifier(apps, schema_editor):
        ResultValueModifier = apps.get_model("viewer", "ResultValueModifier")
        for value, display_name in modifier:
            ResultValueModifier(
                data_type=value,
                display_name=display_name,
            ).save()

    def depopulate_modifier(apps, schema_editor):
        ResultValueModifier = apps.get_model("viewer", "ResultValueModifier")
        ResultValueModifier.objects.all().delete()


    def populate_data_type(apps, schema_editor):
        ResultValueDataType = apps.get_model("viewer", "ResultValueDataType")
        for value, db_type in data_type:
            ResultValueDataType(
                data_type=value,
                display_name=db_type,
            ).save()


    def depopulate_data_type(apps, schema_editor):
        ResultValueDataType = apps.get_model("viewer", "ResultValueDataType")
        ResultValueDataType.objects.all().delete()


    dependencies = [
        ('viewer', '0113_result_resultvaluedatatype_resultvaluemodifier'),
    ]

    operations = [
        migrations.RunPython(populate_modifier, depopulate_modifier),
        migrations.RunPython(populate_data_type, depopulate_data_type),
    ]
