# Generated by Django 3.2.25 on 2025-05-20 09:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0113_auto_20250513_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='state',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
