# Generated by Django 3.2.25 on 2025-04-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0114_auto_20250430_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultvaluedatatype',
            old_name='display_name',
            new_name='db_type',
        ),
        migrations.RenameField(
            model_name='resultvaluemodifier',
            old_name='data_type',
            new_name='modifier',
        ),
    ]
