# Generated by Django 3.2.25 on 2025-04-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0115_auto_20250430_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultvaluedatatype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resultvaluemodifier',
            name='id',
        ),
        migrations.AlterField(
            model_name='resultvaluedatatype',
            name='data_type',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultvaluemodifier',
            name='modifier',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
