# Generated by Django 3.2.25 on 2025-05-02 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0116_auto_20250430_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultvaluemodifier',
            old_name='display_name',
            new_name='django_operator',
        ),
        migrations.AddField(
            model_name='result',
            name='compound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.compound'),
        ),
        migrations.AddField(
            model_name='result',
            name='site_observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation'),
        ),
        migrations.AddField(
            model_name='result',
            name='unit',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ResultUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='assay_data/')),
                ('upload_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.target')),
                ('uploaded_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='result_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.resultupload'),
        ),
    ]
