# Generated by Django 3.2.25 on 2025-05-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0124_result_parsing_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_property', models.TextField()),
                ('unit', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='unit',
        ),
        migrations.AddField(
            model_name='result',
            name='result_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.resultproperty'),
        ),
    ]
