# Generated by Django 3.2.25 on 2025-05-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0126_alter_result_result_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='smiles_mol',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='smiles_mol',
            field=models.TextField(editable=False, null=True),
        ),
    ]
