# Generated by Django 3.2.25 on 2025-05-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0126_alter_result_result_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='smiles_mol',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='smiles_mol',
            field=models.BinaryField(null=True),
        ),
    ]
