# Generated by Django 3.2.25 on 2025-05-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0127_compound_smiles_mol'),
    ]

    operations = [
        # models.py add BinaryField, convert to appropriate rdkit mol type
        migrations.RunSQL(
            sql="""
                ALTER TABLE viewer_compound
                ALTER COLUMN smiles_mol TYPE mol
                USING mol_from_smiles(smiles::cstring);
            """,
            reverse_sql="""
                ALTER TABLE viewer_compound
                ALTER COLUMN smiles_mol DROP DEFAULT,
                ALTER COLUMN smiles_mol SET DATA TYPE bytea
                USING NULL;
            """
        ),
        # add rdkit index to the column
        migrations.RunSQL(
            sql="CREATE INDEX smiles_mol_idx ON viewer_compound USING gist(smiles_mol);",
            reverse_sql="DROP INDEX smiles_mol_idx;"
        ),
        migrations.RunSQL(
            sql="""
            UPDATE viewer_compound
            SET smiles_mol = mol_from_smiles(smiles::cstring)
            WHERE smiles IS NOT NULL;
            """,
            reverse_sql="UPDATE viewer_compound SET smiles_mol = NULL",
        ),
        # function to convert SMILES to rdkit.mol type
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION sync_mol_column()
            RETURNS trigger AS $$
            DECLARE
                smiles_col TEXT := TG_ARGV[0];
                mol_col TEXT := TG_ARGV[1];
                smiles TEXT;
                mol MOL;
            BEGIN
                EXECUTE format('SELECT ($1).%I', smiles_col)
                INTO smiles
                USING NEW;

                IF smiles IS NOT NULL THEN
                    BEGIN
                        mol := mol_from_smiles(smiles);
                    EXCEPTION WHEN OTHERS THEN
                        RAISE WARNING 'Could not create molecule from SMILES: %', smiles;
                        mol := NULL;
                    END;
                ELSE
                    mol := NULL;
                END IF;

                -- Assign to the mol column explicitly by checking its name
                IF mol_col = 'smiles_mol' THEN
                    NEW.smiles_mol := mol;
                ELSIF mol_col = 'another_mol_column' THEN
                    NEW.another_mol_column := mol;
                ELSE
                    RAISE WARNING 'Unknown mol column: %', mol_col;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            """,
            reverse_sql="DROP FUNCTION IF EXISTS sync_mol_column();"
        ),
        # trigger function for compound table
        migrations.RunSQL(
            """
            CREATE TRIGGER update_compound_mol_trigger
            BEFORE INSERT OR UPDATE ON viewer_compound
            FOR EACH ROW
            EXECUTE FUNCTION sync_mol_column('smiles', 'smiles_mol');
            """,
            reverse_sql="DROP TRIGGER IF EXISTS update_compound_mol_trigger ON viewer_compound;"
        ),
    ]
