# Generated by Django 3.2.25 on 2025-05-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0127_auto_20250522_1516'),
    ]

    # lots happening here..
    operations = [
        # install extension to postgres
        migrations.RunSQL('create extension if not exists rdkit;'),
        # models.py adds BinaryField, convert to appropriate rdkit mol type
        migrations.RunSQL(
            sql="""
                ALTER TABLE viewer_compound
                ALTER COLUMN smiles_mol TYPE mol
                USING mol_from_smiles(smiles::cstring);
                ALTER TABLE viewer_siteobservation
                ALTER COLUMN smiles_mol TYPE mol
                USING mol_from_smiles(smiles::cstring);
            """,
            reverse_sql="""
                ALTER TABLE viewer_compound
                ALTER COLUMN smiles_mol DROP DEFAULT,
                ALTER COLUMN smiles_mol SET DATA TYPE bytea
                USING NULL;
                ALTER TABLE viewer_siteobservation
                ALTER COLUMN smiles_mol DROP DEFAULT,
                ALTER COLUMN smiles_mol SET DATA TYPE bytea
                USING NULL;
            """,
        ),
        # add rdkit index to the column
        migrations.RunSQL(
            sql="""
            CREATE INDEX compound_smiles_mol_idx
            ON viewer_compound USING gist(smiles_mol);
            CREATE INDEX siteobservation_smiles_mol_idx
            ON viewer_siteobservation USING gist(smiles_mol);
            """,
            reverse_sql="""
            DROP INDEX compound_smiles_mol_idx;
            DROP INDEX siteobservation_smiles_mol_idx;
            """,
        ),
        # populate smiles_mol field from existing smiles field
        migrations.RunSQL(
            sql="""
            UPDATE viewer_compound
            SET smiles_mol = mol_from_smiles(smiles::cstring)
            WHERE smiles IS NOT NULL;
            UPDATE viewer_siteobservation
            SET smiles_mol = mol_from_smiles(smiles::cstring)
            WHERE smiles IS NOT NULL;
            """,
            reverse_sql="""
            UPDATE viewer_compound SET smiles_mol = NULL;
            UPDATE viewer_siteobservation SET smiles_mol = NULL;
            """,
        ),
        # function to convert SMILES to rdkit.mol type. This is called
        # by triggers that automatically add rdkit.mol type to
        # smiles_mol column in both compound and siteobservation
        # tables
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION sync_mol_column()
            RETURNS trigger AS $$
            DECLARE
                smiles TEXT;
                mol MOL;
            BEGIN
                smiles := NEW.smiles;

                IF smiles IS NOT NULL THEN
                    BEGIN
                        mol := mol_from_smiles(smiles);
                    EXCEPTION WHEN OTHERS THEN
                        RAISE WARNING 'Could not create molecule from SMILES: %', smiles;
                        mol := NULL;
                    END;
                ELSE
                    mol := NULL;
                END IF;

                NEW.smiles_mol := mol;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS sync_mol_column();"
        ),
        # trigger functions for compound and siteobservation
        # tables. these call the previous function
        migrations.RunSQL(
            """
            CREATE TRIGGER update_compound_mol_trigger
            BEFORE INSERT OR UPDATE ON viewer_compound
            FOR EACH ROW
            EXECUTE FUNCTION sync_mol_column('smiles', 'smiles_mol');
            CREATE TRIGGER update_siteobservation_mol_trigger
            BEFORE INSERT OR UPDATE ON viewer_siteobservation
            FOR EACH ROW
            EXECUTE FUNCTION sync_mol_column('smiles', 'smiles_mol');
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS update_compound_mol_trigger ON viewer_compound;
            DROP TRIGGER IF EXISTS update_siteobservation_mol_trigger
            ON viewer_siteobservation;
            """,
        ),
    ]
