# Generated by Django 3.2.25 on 2025-06-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0127_resultproperty_unique_result_property_and_unit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resultproperty',
            name='unique_result_property_and_unit',
        ),
        migrations.AddField(
            model_name='resultproperty',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.target'),
        ),
        migrations.AddConstraint(
            model_name='resultproperty',
            constraint=models.UniqueConstraint(fields=('result_property', 'unit', 'target'), name='unique_result_property_target_unit'),
        ),
    ]
