# Generated by Django 3.2.25 on 2025-06-19 12:11

from django.db import migrations
from django.db.models import F
from django.contrib.postgres.aggregates import ArrayAgg


class Migration(migrations.Migration):

    def link_target(apps, schema_editor):
        ResultProperty = apps.get_model("viewer", "ResultProperty")
        Result = apps.get_model("viewer", "Result")
        Target = apps.get_model("viewer", "Target")

        qs = Result.objects.annotate(target=F('result_upload__target'))
        outer_qs = qs.order_by(
            'result_property',
            'target',
        ).values(
            'result_property',
        ).annotate(
            targets_by_prop=ArrayAgg('target', distinct=True),
        )
        for outer_el in outer_qs:
            targets = outer_el['targets_by_prop']
            prop = ResultProperty.objects.get(pk=outer_el['result_property'])
            if len(targets) > 1:
                for target_id in targets[1:]:
                    target = Target.objects.get(pk=target_id)
                    duplicate = ResultProperty.objects.get(pk=prop.pk)
                    duplicate.pk = None
                    duplicate.target = target
                    duplicate.save()

                    for result in qs.filter(
                        target=target,
                        result_property=prop
                    ):
                        result.result_property = duplicate
                        result.save()

            target = Target.objects.get(pk=targets[0])
            prop.target = target
            prop.save()


    def unlink_target(apps, schema_editor):
        pass


    dependencies = [
        ('viewer', '0128_auto_20250619_1141'),
    ]

    operations = [
        migrations.RunPython(link_target, unlink_target),
    ]
