# Generated by Django 3.2.25 on 2025-06-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0129_auto_20250619_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultproperty',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultproperty',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
