# Generated by Django 3.2.25 on 2025-07-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0130_auto_20250626_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultproperty',
            name='data_type',
            field=models.ForeignKey(default='text', on_delete=django.db.models.deletion.CASCADE, to='viewer.resultvaluedatatype'),
            preserve_default=False,
        ),
    ]
