# Generated by Django 3.2.25 on 2025-07-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    def move_property(apps, schema_editor):
        ResultProperty = apps.get_model("viewer", "ResultProperty")
        Result = apps.get_model("viewer", "Result")

        for prop in ResultProperty.objects.all():
            results = Result.objects.filter(
                result_property=prop,
            )

            data_type = results.values('data_type').distinct()

            if data_type.count() != 1:
                raise ValueError(f'Multiple data types for {prop.result_property}')

            prop.data_type = results.first().data_type
            prop.save()


    def unmove_property(apps, schema_editor):
        ResultProperty = apps.get_model("viewer", "ResultProperty")
        Result = apps.get_model("viewer", "Result")

        for prop in ResultProperty.objects.all():
            for result in Result.objects.filter(result_property=prop):
                result.data_type = prop.data_type
                result.save()


    dependencies = [
        ('viewer', '0131_resultproperty_data_type'),
    ]

    operations = [
        migrations.RunPython(move_property, unmove_property),
    ]
