# Generated by Django 3.2.25 on 2025-07-03 13:15

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0133_remove_result_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('upload_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('plotly_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('notebook_path', models.TextField(null=True)),
                ('squonk_project_id', models.TextField(null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.project')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.target')),
            ],
        ),
    ]
