# Generated by Django 3.2.25 on 2025-07-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0134_plotdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotDataIdentifierType',
            fields=[
                ('identifier', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='plotdata',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.plotdataidentifiertype'),
        ),
    ]
