# Generated by Django 3.2.25 on 2025-07-03 14:29

from django.db import migrations

data_types = ('observation_code', 'compound_code', 'computed_molecule_code')

class Migration(migrations.Migration):

    def populate_types(apps, schema_editor):
        PlotDataIdentifierType = apps.get_model("viewer", "PlotDataIdentifierType")
        for d in data_types:
            PlotDataIdentifierType(identifier=d).save()


    def depopulate_types(apps, schema_editor):
        pass


    dependencies = [
        ('viewer', '0135_auto_20250703_1428'),
    ]

    operations = [
        migrations.RunPython(populate_types, depopulate_types),
    ]
