# Generated by Django 3.2.25 on 2025-07-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0136_auto_20250703_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotdata',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.plotdataidentifiertype'),
        ),
    ]
