# Generated by Django 3.2.25 on 2025-08-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0138_experiment_refinement_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteObservationComputedMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmsd', models.FloatField()),
                ('computed_molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.computedmolecule')),
                ('site_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation')),
            ],
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='computed_molecules',
            field=models.ManyToManyField(through='viewer.SiteObservationComputedMolecule', to='viewer.ComputedMolecule'),
        ),
        migrations.AddConstraint(
            model_name='siteobservationcomputedmolecule',
            constraint=models.UniqueConstraint(fields=('site_observation', 'computed_molecule'), name='unique_siteobservation_computedmolecule'),
        ),
    ]
