# Generated by Django 3.2.25 on 2025-08-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0139_auto_20250813_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteobservationcomputedmolecule',
            name='rmsd',
            field=models.FloatField(null=True),
        ),
    ]
