# Generated by Django 3.2.25 on 2025-08-27 13:31

from django.db import migrations
from rdkit import Chem


# situations to handle here:
# - one new compound is equal to potentially multiple old ones
#   -  what do I do then?
# - otherwise, transfer missing attributes to old cmp
# - link the computedmolecules to old cmp
# - delete the new one

# I don't think there's multiple new ones pointing to single old comp,
# it should be able to find one.

class Migration(migrations.Migration):

    def deduplicate_compounds(apps, schema_editor):
        Target = apps.get_model("viewer", "Target")
        Compound = apps.get_model("viewer", "Compound")
        Experiment = apps.get_model("viewer", "Experiment")
        ExperimentUpload = apps.get_model("viewer", "ExperimentUpload")
        ExperimentCompound = apps.get_model("viewer", "ExperimentCompound")
        ComputedMolecule = apps.get_model("viewer", "ComputedMolecule")


        # calculate all exisiting flattened inchi keys
        compound_pk = ExperimentCompound.objects.values('compound')
        for cmpd in Compound.objects.filter(pk__in=compound_pk):
            mol = Chem.MolFromSmiles(cmpd.smiles, sanitize=True)
            if mol:
                Chem.RemoveStereochemistry(mol)
                inchi_key = Chem.inchi.MolToInchiKey(mol)
                cmpd.inchi_key = inchi_key
                cmpd.save()


        # find the pairs that are going to be merged. NB! only within
        # target
        deletables = []
        for target in Target.objects.all():
            # ok this is a bit unnerving - Compound.filter_manager on
            # targets returns a couple fewer compounds than the one
            # below. The one below seems correct, so filter_manager is
            # malfunctioning?
            compound_qs = Compound.objects.filter(
                pk__in=ExperimentCompound.objects.filter(
                    experiment_id__in=Experiment.objects.filter(
                        experiment_upload__in=ExperimentUpload.objects.filter(
                            target=target,
                        ).values('pk'),
                    ).values('pk'),
                ).values('compound'),
            ).filter(
                # i'm 99% sure this is unnecessary, but oh well
                pk__in=compound_pk,
            )

            computed_qs = Compound.objects.filter(
                pk__in=ComputedMolecule.objects.filter(
                    computed_set__target=target,
                ).values('compound'),
                inchi_key__in=compound_qs.values_list('inchi_key', flat=True)
            )
            for computed_comp in computed_qs:
                # there's a chance that there are multiple, but in
                # this instance, it doesn't matter
                duplicated = compound_qs.filter(
                    inchi_key=computed_comp.inchi_key,
                ).first()

                # only these 2 fields are populated on
                # computedmolecule's compound and not on regular
                # compound
                duplicated.inchi = computed_comp.inchi
                duplicated.description = computed_comp.description
                duplicated.save()

                # transfer foreign keys. really only need to worry
                # about computedmolecule
                for cmol in computed_comp.computedmolecule_set.all():
                    cmol.compound = duplicated
                    cmol.save()

                deletables.append(computed_comp.pk)


        # should be no issues deleting the molecules now
        Compound.objects.filter(pk__in=deletables).delete()




    def dededuplicate_compounds(apps, schema_editor):
        pass

    dependencies = [
        ('viewer', '0140_alter_siteobservationcomputedmolecule_rmsd'),
    ]

    operations = [
        migrations.RunPython(deduplicate_compounds, dededuplicate_compounds),
    ]
