# Generated by Django 3.2.25 on 2025-08-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0128_auto_20250516_1015'),
        ('viewer', '0140_alter_siteobservationcomputedmolecule_rmsd'),
    ]

    operations = [
    ]
