# Generated by Django 3.2.25 on 2025-08-27 13:31

from django.db import migrations
from rdkit import Chem


class Migration(migrations.Migration):

    def deduplicate_compounds(apps, schema_editor):
        Compound = apps.get_model("viewer", "Compound")
        ComputedMolecule = apps.get_model("viewer", "ComputedMolecule")

        computed_qs = Compound.objects.filter(
            pk__in=ComputedMolecule.objects.values('compound'),
        )
        compound_qs = Compound.objects.exclude(pk__in=computed_qs.values('pk'))

        # calculate all exisiting flattened inchi keys
        for cmpd in compound_qs:
            mol = Chem.MolFromSmiles(cmpd.smiles, sanitize=True)
            if mol:
                Chem.RemoveStereochemistry(mol)
                inchi_key = Chem.inchi.MolToInchiKey(mol)
                cmpd.inchi_key = inchi_key
                cmpd.save()


        # refresh, just in case
        compound_qs = Compound.objects.exclude(pk__in=computed_qs.values('pk'))

        # these are now the ones that existed previously but were
        # duplicated during cset upload
        duplicated = compound_qs.filter(
            inchi_key__in=computed_qs.values('inchi_key'),
        )




    def dededuplicate_compounds(apps, schema_editor):
        pass

    dependencies = [
        ('viewer', '0140_alter_siteobservationcomputedmolecule_rmsd'),
    ]

    operations = [
        migrations.RunPython(deduplicate_compounds, dededuplicate_compounds),
    ]
