# Generated by Django 3.2.25 on 2025-09-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0141_auto_20250827_1331'),
        ('viewer', '0141_merge_20250821_1022'),
    ]

    operations = [
    ]
