# Generated by Django 3.2.25 on 2025-09-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0114_alter_snapshot_state'),
        ('viewer', '0142_merge_20250909_1530'),
    ]

    operations = [
    ]
