# Generated by Django 3.2.25 on 2025-09-18 13:31

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0143_merge_20250916_1256'),
    ]

    operations = [
        VectorExtension()
    ]
