# Generated by Django 3.2.25 on 2025-09-18 13:50

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.halfvec


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0144_auto_20250918_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtomCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords', pgvector.django.halfvec.HalfVectorField(dimensions=3)),
                ('site_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atom_coordinates', to='viewer.siteobservation')),
            ],
        ),
    ]
