# Generated by Django 3.2.25 on 2025-09-18 13:50

from django.db import migrations

# TODO: data migration to load existing ligand coords to database

class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0145_atomcoordinates'),
    ]

    operations = [
    ]
