# Generated by Django 3.2.25 on 2025-09-18 13:50

from pathlib import Path

from django.db import migrations
from django.conf import settings
from rdkit import Chem

# TODO: data migration to load existing ligand coords to database

class Migration(migrations.Migration):

    def import_ligands(apps, schema_editor):
        SiteObservation = apps.get_model("viewer", "SiteObservation")
        AtomCoordinates = apps.get_model("viewer", "AtomCoordinates")

        for so in SiteObservation.objects.all():
            if so.ligand_mol:
                molpath = Path(settings.MEDIA_ROOT).joinpath(so.ligand_mol.name)
            if not molpath.exists():
                continue

            mol = Chem.MolFromMolFile(str(molpath))
            conf = mol.GetConformer()

            for atom in mol.GetAtoms():
                pos = conf.GetAtomPosition(atom.GetIdx())
                atom = AtomCoordinates(
                    site_observation=so,
                    coords=list(pos),
                    atom_number=atom.GetAtomicNum(),
                )
                atom.save()


    def deimport_ligands(apps, schema_editor):
        pass

    dependencies = [
        ('viewer', '0145_atomcoordinates'),
    ]

    operations = [
        migrations.RunPython(import_ligands, deimport_ligands),
    ]
