# Generated by Django 3.2.25 on 2025-09-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0146_auto_20250918_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomcoordinates',
            name='atom_number',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
