# Generated by Django 3.2.25 on 2025-11-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0146_auto_20250918_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='altloc',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='altloc',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='atomcoordinates',
            name='atom_number',
            field=models.SmallIntegerField(),
        ),
    ]
