# Generated by Django 3.2.25 on 2025-11-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0146_auto_20250918_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='altloc',
            field=models.CharField(blank=True, max_length=1, default='x'),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='altloc',
            field=models.CharField(blank=True, max_length=1, default='x'),
        ),
        migrations.AlterField(
            model_name='atomcoordinates',
            name='atom_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AddField(
            model_name='experimentupload',
            name='assembly_transforms',
            field=models.FileField(max_length=255, null=True, upload_to='experiment-upload/'),
        ),
        migrations.AlterField(
            model_name='experimentupload',
            name='conformer_site_transforms',
            field=models.FileField(max_length=255, null=True, upload_to='experiment-upload/'),
        ),
        migrations.AlterField(
            model_name='experimentupload',
            name='neighbourhood_transforms',
            field=models.FileField(max_length=255, null=True, upload_to='experiment-upload/'),
        ),
        migrations.AlterField(
            model_name='experimentupload',
            name='reference_structure_transforms',
            field=models.FileField(max_length=255, null=True, upload_to='experiment-upload/'),
        ),

    ]
