# Generated by Django 5.2.7 on 2025-10-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0146_auto_20250918_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomcoordinates',
            name='atom_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='computed_molecules',
            field=models.ManyToManyField(related_name='computed_set', through='viewer.ComputedSetComputedMolecule', through_fields=('computed_set', 'computed_molecule'), to='viewer.computedmolecule'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='compounds',
            field=models.ManyToManyField(through='viewer.ExperimentCompound', through_fields=('experiment', 'compound'), to='viewer.compound'),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='computed_molecules',
            field=models.ManyToManyField(through='viewer.SiteObservationComputedMolecule', through_fields=('site_observation', 'computed_molecule'), to='viewer.computedmolecule'),
        ),
        migrations.AlterField(
            model_name='siteobservationtag',
            name='site_observations',
            field=models.ManyToManyField(through='viewer.SiteObvsSiteObservationTag', through_fields=('site_obvs_tag', 'site_observation'), to='viewer.siteobservation'),
        ),
        migrations.AlterField(
            model_name='xtalform',
            name='quat_assembly',
            field=models.ManyToManyField(through='viewer.XtalformQuatAssembly', through_fields=('xtalform', 'quat_assembly'), to='viewer.quatassembly'),
        ),
    ]
