# Generated by Django 5.2.7 on 2025-11-11 15:57

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0147_alter_atomcoordinates_atom_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='virtual_identifier',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ACDEFGHJKLMNPRSTUVWXYZ345679', blank=True, length=4, max_length=4, null=True, prefix=''),
        ),
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='virtual_molecule_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='virtual_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='virtual_pdb_info',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='virtual_rationale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='virtual_ref_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='computed_inspirations',
            field=models.ManyToManyField(blank=True, to='viewer.siteobservation'),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='virtual_identifier',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ACDEFGHJKLMNPRSTUVWXYZ345679', blank=True, length=4, max_length=4, null=True, prefix=''),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='virtual_molecule_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='virtual_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='virtual_pdb_info',
            field=models.FileField(max_length=255, null=True, upload_to='computed_set_data/'),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='virtual_rationale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='virtual_ref_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsiteobservation',
            name='chain_id',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsiteobservation',
            name='seq_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='canon_site_conf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.canonsiteconf'),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='chain_id',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.experiment'),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='seq_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='xtalform_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.xtalformsite'),
        ),
        migrations.CreateModel(
            name='ComputedSetSiteObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.computedset')),
                ('site_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation')),
            ],
        ),
        migrations.AddField(
            model_name='computedset',
            name='site_observations',
            field=models.ManyToManyField(related_name='computed_set', through='viewer.ComputedSetSiteObservation', through_fields=('computed_set', 'site_observation'), to='viewer.siteobservation'),
        ),
        migrations.AddConstraint(
            model_name='computedsetsiteobservation',
            constraint=models.UniqueConstraint(fields=('computed_set', 'site_observation'), name='unique_computedsetsiteobservation'),
        ),
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='virtual_ligand_mol',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='virtual_ligand_mol',
            field=models.FileField(max_length=255, null=True, upload_to='computed_set_data/'),
        ),
        migrations.AddField(
            model_name='historicalsiteobservation',
            name='virtual_ref_observation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viewer.siteobservation'),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='virtual_ref_observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation'),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='computed_observations',
            field=models.ManyToManyField(blank=True, to='viewer.siteobservation'),
        ),
        migrations.CreateModel(
            name='SiteObservationComputedSiteObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmsd', models.FloatField(null=True)),
                ('computed_site_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhs_site_observations', to='viewer.siteobservation')),
                ('site_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lhs_site_observations', to='viewer.siteobservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_observation', 'computed_site_observation'), name='unique_siteobservation_computedsiteobservation')],
            },
        ),
    ]
