# Generated by Django 3.2.25 on 2025-11-28 11:41

from pathlib import Path

from django.conf import settings
from django.db import migrations
from django.db.models import CharField, Value, F
from django.db.models.functions import Concat

class Migration(migrations.Migration):

    def migrate_v3(apps, schema_editor):
        SiteObservation = apps.get_model("viewer", "SiteObservation")
        XtalformSite = apps.get_model("viewer", "XtalformSite")
        CanonSiteConf = apps.get_model("viewer", "CanonSiteConf")
        CanonSite = apps.get_model("viewer", "CanonSite")

        # this code is from download module, presumably thoroughly tested
        so_qs = SiteObservation.objects.annotate(
            oldname=Concat(
                F('experiment__code'),
                Value('_'),
                F('chain_id'),
                Value('_'),
                F('seq_id'),
                Value('_'),
                F('version'),
                Value('_'),
                F('canon_site_conf__canon_site__name'),
                Value('+'),
                F('canon_site_conf__canon_site__version'),
                output_field=CharField(),
            ),
            # canon site names don't contain version, can create it here
            newname=Concat(
                F('experiment__code'),
                Value('_'),
                F('chain_id'),
                Value('_'),
                F('seq_id'),
                Value('_x_'),
                F('version'),
                Value('_'),
                F('canon_site_conf__canon_site__name'),
                Value('+x+'),
                F('canon_site_conf__canon_site__version'),
                output_field=CharField(),
            ),
        )

        file_fields = ('bound_file', 'apo_solv_file', 'apo_desolv_file', 'apo_file', 'sigmaa_file', 'sigmaa_file', 'diff_file', 'event_file', 'artefacts_file', 'pdb_header_file', 'ligand_mol', 'ligand_smiles', 'ligand_pdb', 'ligand_sdf')
        ccps = ('sigmaa_file', 'diff_file', 'event_file')


        for so in so_qs:
            # longcode: CHIKV_MacB-x0294_A_501_v1
            splits = so.longcode.split('_')
            elem = splits[:-1] + ['x'] + splits[-1:]
            so.longcode = '_'.join(elem)



            for f in file_fields:
                model_attr = getattr(so, f)
                if model_attr and model_attr != 'None':
                    path = Path(model_attr.name)
                    newname = path.parts[-1].replace(so.oldname, so.newname)

                    newpath = Path(*path.parts[:-1], newname)
                    Path(settings.MEDIA_ROOT, model_attr.name).rename(
                        Path(settings.MEDIA_ROOT, newpath)
                    )
                    setattr(so, f, str(newpath))

            so.save()

            for f in ccps:
                model_attr = getattr(so, f)
                if model_attr and model_attr != 'None':
                    path = Path(model_attr.name)
                    oldpath = Path(*path.parts[:-1], f'{path.stem}_crystallographic{path.suffix}')
                    newname = path.parts[-1].replace(so.oldname, so.newname)
                    newpath = Path(newname)
                    newname = f'{newpath.stem}_crystallographic{newpath.suffix}'
                    newpath = Path(*path.parts[:-1], newname)
                    Path(settings.MEDIA_ROOT, oldpath).rename(
                        Path(settings.MEDIA_ROOT, newpath)
                    )


        for xs in XtalformSite.objects.all():
            xs.residues = ['/'.join(r.split('/')[:-1] + ['x'] + r.split('/')[-1:]) for r in xs.residues]
            xs.xtalform_site_id = '/'.join([xs.xtalform_site_id, 'x'])
            xs.save()

        for cf in CanonSiteConf.objects.all():
            cf.name = '+'.join([cf.name, 'x'])
            cf.save()

        for cn in CanonSite.objects.all():
            cn.name = '+'.join([cn.name, 'x'])
            splits = cn.centroid_res.split('_')
            elem = splits[:-1] + ['x'] + splits[-1:]
            cn.centroid_res = '_'.join(elem)
            cn.save()


    def demigrate_v3(apps, schema_editor):
        pass


    dependencies = [
        ('viewer', '0147_auto_20251127_1530'),
    ]

    operations = [
        migrations.RunPython(migrate_v3, demigrate_v3),
    ]
