# Generated by Django 3.2.25 on 2025-09-24 19:00

from django.db import migrations
import pgvector.django.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0147_atomcoordinates_atom_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='atomcoordinates',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['coords'], m=16, name='pgvector_coord_index', opclasses=['halfvec_l2_ops']),
        ),
    ]
