# Generated by Django 5.2.7 on 2025-12-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0147_alter_atomcoordinates_atom_number_and_more'),
        ('viewer', '0148_auto_20251128_1141'),
    ]

    operations = [
    ]
