# Generated by Django 5.2.7 on 2025-11-11 15:58
import os
from pathlib import Path

from rdkit import Chem

from django.db import migrations
from django.conf import settings

from viewer.models import ResultValueDataType


class Migration(migrations.Migration):

    def merge_computedmolecule(apps, schema_editor):
        SiteObservation = apps.get_model("viewer", "SiteObservation")
        ComputedMolecule = apps.get_model("viewer", "ComputedMolecule")
        AtomCoordinates = apps.get_model("viewer", "AtomCoordinates")
        Result = apps.get_model("viewer", "Result")
        ResultProperty = apps.get_model("viewer", "ResultProperty")
        ResultUpload = apps.get_model("viewer", "ResultUpload")
        ResultValueDataType = apps.get_model("viewer", "ResultValueDataType")
        ScoreDescription = apps.get_model("viewer", "ScoreDescription")
        NumericalScoreValues = apps.get_model("viewer", "NumericalScoreValues")
        TextScoreValues = apps.get_model("viewer", "TextScoreValues")


        cmp_set_folder = os.path.join(
            settings.MEDIA_ROOT, settings.COMPUTED_SET_MEDIA_DIRECTORY
        )
        if not os.path.isdir(cmp_set_folder):
            os.mkdir(cmp_set_folder)

        # move and save the compound set
        sdf_root = Path(settings.MEDIA_ROOT).joinpath(settings.COMPUTED_SET_MEDIA_DIRECTORY)

        # loop through computed molecules and recreate them as site
        # observations
        for cm in ComputedMolecule.objects.all():

            # computed molecule usually has reference site
            # observation. but not always
            if cm.pdb:
                pose = cm.pdb.pose
                pdb_info = None
                xtalform_site = cm.pdb.xtalform_site
                canon_site_conf = cm.pdb.canon_site_conf
            else:
                # There are no such objects in the db atm.
                pose = None
                pdb_info = cm.pdb_info
                xtalform_site = None
                canon_site_conf = None

            # TODO: they need ref. site observation...
            so = SiteObservation(
                cmpd=cm.compound,
                xtalform_site=xtalform_site,
                canon_site_conf=canon_site_conf,
                pose=pose,
                smiles=cm.smiles,
                virtual_name=cm.name,
                virtual_molecule_name=cm.molecule_name,
                virtual_identifier=cm.identifier,
                virtual_ref_url=cm.ref_url,
                virtual_rationale=cm.rationale,
                virtual_ref_observation=cm.pdb,
                virtual_pdb_info=pdb_info,
            )
            so.save()
            so.computed_inspirations.add(*list(cm.computed_inspirations.all()))

            mol = Chem.MolFromMolBlock(cm.sdf_info)
            conf = mol.GetConformer()

            for atom in mol.GetAtoms():
                pos = conf.GetAtomPosition(atom.GetIdx())
                atom = AtomCoordinates(
                    site_observation=so,
                    coords=list(pos),
                    atom_number=atom.GetAtomicNum(),
                )
                atom.save()

            target = None
            # file content used do be in the db, write the files and
            # populate file field in so
            for cset in cm.computed_set.all():
                cset.site_observations.add(so)

                # this is duplicating files. do I want that?
                filename = f"{cset.name}_upload_{cset.md_ordinal}_{cm.name}_{cm.molecule_name}_{cm.identifier}.mol"
                # save sdf_info to file
                sdf_filename = sdf_root.joinpath(filename)
                with open(sdf_filename, "w") as f:
                    f.write(cm.sdf_info)

                # hold on, this will be overwriting the values
                so.virtual_ligand_mol = filename
                so.save()

                # grab for later
                target = cset.target

            for score in NumericalScoreValues.objects.filter(compound=cm):
                # I don't think I need ResultUpload... right?

                data_type = ResultValueDataType.objects.get(data_type='float')

                # unit=None - there are currently no units in scores,
                # no point trying to deduce anything
                result_property, _ = ResultProperty.objects.get_or_create(
                    result_property=score.score.name,
                    unit=None,
                    target=target,
                    data_type=data_type,
                )
                result = Result(
                    raw_value=score.value,
                    float_value=score.value,
                    site_observation=so,
                    result_property=result_property,
                )
                result.save()

            for score in TextScoreValues.objects.filter(compound=cm):

                data_type = ResultValueDataType.objects.get(data_type='text')
                result_property, _ = ResultProperty.objects.get_or_create(
                    result_property=score.score.name,
                    unit=None,
                    target=target,
                    data_type=data_type,
                )
                result = Result(
                    raw_value=score.value,
                    text_value=score.value,
                    site_observation=so,
                    result_property=result_property,
                )
                result.save()




        # this doesn't exist so there's no need to convert but seems
        # like needed in the future
        ResultValueDataType(data_type='boolean', db_type='boolean').save()


            # questions for max:
            # - is it necessary to link the results to ComputedSet as they used to be?
            # - is it necessary to store Score.description data field?


    def demerge_computedmolecule(apps, schema_editor):
        pass

    dependencies = [
        ('viewer', '0148_historicalsiteobservation_virtual_identifier_and_more'),
    ]

    operations = [
        migrations.RunPython(merge_computedmolecule, demerge_computedmolecule),
    ]
