# Generated by Django 5.2.10 on 2026-01-28 15:15
import logging

from django.db import migrations
from django.db.models import Count, F, Value
from django.db.models.functions import Left, Length, Reverse, StrIndex
from django.contrib.postgres.aggregates import ArrayAgg

from viewer.utils import alphanumerator, strip_exp_code

logger = logging.getLogger(__name__)

class Migration(migrations.Migration):

    def fix_shortcodes(apps, schema_editor):
        SiteObservation = apps.get_model("viewer", "SiteObservation")
        ComputedMolecule = apps.get_model("viewer", "ComputedMolecule")
        Target = apps.get_model("viewer", "Target")
        Experiment = apps.get_model("viewer", "Experiment")


        so_qs = SiteObservation.objects.annotate(
            sitecount=Count("canon_site_conf__canon_site__canonsiteconf__siteobservation"),
            last_occur=StrIndex(Reverse(F('longcode')), Value('_')),
            # longcode without version, this is how they're grouped
            mediumcode=Left('longcode',Length('longcode')-F('last_occur')),
        )

        for target in Target.objects.all():
            target_codes = set()
            for experiment in Experiment.objects.filter(experiment_upload__target=target):
                suffix = alphanumerator()
                qs = so_qs.filter(
                    experiment=experiment,
                ).order_by(
                    # abusing the fact that while conformer site can
                    # change, canon site won't (and doesn't at least in
                    # current database)
                    '-sitecount',
                    'mediumcode'
                ).values(
                    'mediumcode',
                ).annotate(
                    obvs=ArrayAgg('id', distinct=True),
                )

                for group in qs:
                    if experiment.type == 1:
                        # manual. code is pdb code
                        code = f"{experiment.code}-{next(suffix)}"
                    else:
                        # model building. generate code
                        try:
                            exp_code_no = strip_exp_code(experiment.code)
                        except ValueError as exc:
                            logger.error(exc.args[1])
                            # error, loading failed, use full code for demo
                            exp_code_no = experiment.code

                        code = f"{experiment.code_prefix}{exp_code_no}{next(suffix)}"

                    if code not in target_codes:
                        target_codes.add(code)
                    else:
                        raise ValueError(
                            f'Code {code} not unique for target {target.id}: {target.title}')

                    # now I have the code for the group.
                    so_group = SiteObservation.objects.filter(
                        pk__in=group['obvs'],
                    ).order_by('version')

                    so_group.update(code=code)
                    cs_qs = ComputedMolecule.objects.filter(pdb__in=so_group.values('pk'))

                    # update codes in connected computedmolecules
                    # again abusing the fact that there are no pdb
                    # uploads, both codes are always the same
                    cs_qs.update(site_observation_code=code)
                    cs_qs.update(reference_code=code)


                    # set the superseded flags
                    so_group.exclude(pk=so_group.last().pk).update(superseded=True)
                    so_group.filter(pk=so_group.last().pk).update(superseded=False)


    def unfix_shortcodes(apps, schema_editor):
        pass


    dependencies = [
        ('viewer', '0149_merge_20251215_1247'),
    ]

    operations = [
        migrations.RunPython(fix_shortcodes, unfix_shortcodes),
    ]
