# Generated by Django 5.2.7 on 2025-12-19 12:57

from django.db import migrations

data_type = (
    ("link", "text"),
)


class Migration(migrations.Migration):

    def add_data_type(apps, schema_editor):
        ResultValueDataType = apps.get_model("viewer", "ResultValueDataType")
        for value, db_type in data_type:
            ResultValueDataType(
                data_type=value,
                db_type=db_type,
            ).save()


    def deadd_data_type(apps, schema_editor):
        pass

    dependencies = [
        ('viewer', '0150_result_experiment'),
    ]

    operations = [
        migrations.RunPython(add_data_type, deadd_data_type),
    ]
