# Generated by Django 5.2.13 on 2026-04-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0150_auto_20260128_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlinks',
            name='request_ip',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='downloadlinks',
            name='request_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='downloadlinks',
            name='file_url',
            field=models.TextField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='downloadlinks',
            name='keep_zip_until',
            field=models.DateTimeField(db_index=True, help_text='The datetime when the tag was created plus the retention time (1 hour at the time of writing)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsiteobservation',
            name='altloc',
            field=models.CharField(blank=True, default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='altloc',
            field=models.CharField(blank=True, default='0', max_length=1),
        ),
    ]
