# Generated by Django 5.2.13 on 2026-04-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0151_downloadlinks_request_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlinks',
            name='deleted',
            field=models.BooleanField(help_text='Set when the download file has been removed from the filesystem.', null=True),
        ),
        migrations.AddField(
            model_name='downloadlinks',
            name='expired_date',
            field=models.DateTimeField(help_text='Set when the download has passed its keep until date. Users should not use records when this is set.', null=True),
        ),
    ]
