# Generated by Django 5.2.13 on 2026-04-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0152_add_downloadlinks_expiry_and_deleted_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlinks',
            name='task_id',
            field=models.TextField(help_text='The task ID assigned to this download (if a Task is launched)', null=True),
        ),
    ]
