# Generated by Django 5.2.7 on 2026-01-12 11:17

from django.db import migrations, models
from viewer.models import DownloadLinks


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0152_result_link_value'),
    ]

    def delete_downloadlinks(apps, schema_editor):
        # remove before changing field type
        DownloadLinks = apps.get_model("viewer", "DownloadLinks")
        DownloadLinks.objects.all().delete()

    operations = [
        migrations.RunPython(delete_downloadlinks,),
        migrations.AlterField(
            model_name='downloadlinks',
            name='proteins',
            field=models.TextField(null=True),
        ),
    ]
