# Generated by Django 5.2.7 on 2026-01-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    """Change DownloadLinks.proteins from JSONField to TextField (#1982).

    This used to begin by deleting every DownloadLinks row ("remove before
    changing field type"). That was never necessary: on PostgreSQL Django emits
    the AlterField below as

        ALTER COLUMN "proteins" TYPE text USING "proteins"::text

    (see ``_using_sql`` in django/db/backends/postgresql/schema.py), which casts
    the existing jsonb values - and NULLs - without complaint.

    It was also destructive far beyond its intent. Written in January 2026 on a
    long-lived feature branch, it only reached staging (ccdc3ced, 2026-07-08) and
    production (7989f44e, 2026-07-23), so the wipe ran at *those* deploys and
    took out every download record made up to then, while leaving the archives
    under media/downloads/ on disk. Static download links handed out before the
    deploy now fail with "file_url should only be provided for static files",
    because DownloadStructuresView.create() can no longer find their record.
    ``viewer/download_restore.py`` rebuilds those rows from the archives.

    The delete is removed here rather than reversed: instances that already ran
    this migration are unaffected (it is recorded as applied, and dropping a
    RunPython changes no migration state), while any database migrating past it
    from now on keeps its download history.

    Rows predating this migration keep their old value - the JSON text
    '["Mpro-x0104_A", ...]', and codes rather than the ids adopted later (see
    DownloadLinks.proteins). Nothing is harmed by that: the column is only ever
    compared for equality when DownloadStructuresView.create() looks for a
    reusable download, and an old value can never equal a newly built one, so a
    legacy record is simply never reused.
    """

    dependencies = [
        ('viewer', '0152_result_link_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlinks',
            name='proteins',
            field=models.TextField(null=True),
        ),
    ]
