# Generated by Django 5.2.13 on 2026-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0153_add_task_id_to_downloadlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alias',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
