# Generated by Django 5.2.7 on 2026-01-21 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0153_alter_downloadlinks_proteins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computedset',
            name='upload_progress',
        ),
        migrations.RemoveField(
            model_name='computedset',
            name='upload_status',
        ),
        migrations.RemoveField(
            model_name='computedset',
            name='upload_task_id',
        ),
        migrations.RemoveField(
            model_name='historicalcomputedset',
            name='upload_progress',
        ),
        migrations.RemoveField(
            model_name='historicalcomputedset',
            name='upload_status',
        ),
        migrations.RemoveField(
            model_name='historicalcomputedset',
            name='upload_task_id',
        ),
        migrations.AddField(
            model_name='result',
            name='computed_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.computedset'),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='method',
            field=models.CharField(blank=True, help_text='The name of the algorithmic method used to generate the compounds (e.g. Fragmenstein)', null=True),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='method_url',
            field=models.TextField(help_text='A url linking to a write-up of the methodology used to create the computed set', null=True),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='method',
            field=models.TextField(blank=True, help_text='The name of the algorithmic method used to generate the compounds (e.g. Fragmenstein)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomputedset',
            name='method',
            field=models.TextField(blank=True, help_text='The name of the algorithmic method used to generate the compounds (e.g. Fragmenstein)', null=True),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='submitted_sdf',
            field=models.FileField(help_text='The original SDF containing the ComputedSet', upload_to='computed_set_data/'),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='upload_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='computedset',
            name='written_sdf_filename',
            field=models.TextField(help_text='The written ComputedSet filename', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomputedset',
            name='method',
            field=models.CharField(blank=True, help_text='The name of the algorithmic method used to generate the compounds (e.g. Fragmenstein)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomputedset',
            name='method_url',
            field=models.TextField(help_text='A url linking to a write-up of the methodology used to create the computed set', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomputedset',
            name='submitted_sdf',
            field=models.TextField(help_text='The original SDF containing the ComputedSet', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcomputedset',
            name='upload_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomputedset',
            name='written_sdf_filename',
            field=models.TextField(help_text='The written ComputedSet filename', null=True),
        ),
    ]
