# Generated by Django 5.2.7 on 2026-01-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0154_remove_computedset_upload_progress_and_more'),
    ]

    operations = [
    ]
