# Generated by Django 5.2.7 on 2026-01-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0154_remove_computedset_upload_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedset',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomputedset',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
