# Generated by Django 5.2.13 on 2026-05-15 15:10

from django.conf import settings
from django.db import migrations, models

LOADER_ROLE = "Loader"


def create_loader_role(apps, schema_editor):
    UserRole = apps.get_model("viewer", "UserRole")
    UserRole.objects.get_or_create(name=LOADER_ROLE)


def remove_loader_role(apps, schema_editor):
    UserRole = apps.get_model("viewer", "UserRole")
    UserRole.objects.filter(name=LOADER_ROLE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0155_downloadlinks_file_url_basename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('users', models.ManyToManyField(blank=True, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_loader_role, remove_loader_role),
    ]
