# Generated by Django 5.2.7 on 2026-02-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0150_auto_20260128_1515'),
        ('viewer', '0155_alter_computedset_name_and_more'),
    ]

    operations = [
    ]
