# Generated by Django 5.2.10 on 2026-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0156_merge_20260212_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteobservation',
            name='computed_inspirations',
        ),
        migrations.AlterField(
            model_name='historicalsiteobservation',
            name='altloc',
            field=models.CharField(blank=True, default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='altloc',
            field=models.CharField(blank=True, default='0', max_length=1),
        ),
    ]
