# Generated by Django 5.2.10 on 2026-04-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0157_remove_siteobservation_computed_inspirations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedInspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='viewer.siteobservation')),
                ('computed_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.computedset')),
                ('site_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='viewer.siteobservation')),
            ],
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='computed_inspirations',
            field=models.ManyToManyField(related_name='inspired_observation', through='viewer.ComputedInspiration', through_fields=('site_observation', 'computed_inspiration'), to='viewer.siteobservation'),
        ),
    ]
