# Generated by Django 5.2.10 on 2026-04-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0158_computedinspiration_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='computedinspiration',
            constraint=models.UniqueConstraint(fields=('site_observation', 'computed_inspiration', 'computed_set'), name='unique_inspirations_computed_set'),
        ),
    ]
