# Generated by Django 5.2.11 on 2026-04-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0159_computedinspiration_unique_inspirations_computed_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlinks',
            name='request_ip',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='downloadlinks',
            name='request_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='downloadlinks',
            name='file_url',
            field=models.TextField(db_index=True, null=True, unique=True),
        ),
    ]
