# Generated by Django 5.2.11 on 2026-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0160_downloadlinks_request_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlinks',
            name='keep_zip_until',
            field=models.DateTimeField(db_index=True, help_text='The datetime when the tag was created plus the retention time (1 hour at the time of writing)', null=True),
        ),
        migrations.AlterField(
            model_name='downloadlinks',
            name='request_ip',
            field=models.TextField(null=True),
        ),
    ]
