# Generated by Django 5.2.11 on 2026-05-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0161_alter_downloadlinks_keep_zip_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprojecttag',
            name='meta_category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='siteobservationtag',
            name='meta_category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionprojecttag',
            name='tag',
            field=models.TextField(help_text='The (unique) name of the tag'),
        ),
        migrations.AlterField(
            model_name='sessionprojecttag',
            name='upload_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='siteobservationtag',
            name='tag',
            field=models.TextField(help_text='The (unique) name of the tag'),
        ),
        migrations.AlterField(
            model_name='siteobservationtag',
            name='upload_name',
            field=models.TextField(null=True),
        ),
    ]
