# Generated by Django 5.2.15 on 2026-06-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0157_downloadlinks_expiry_reason'),
        ('viewer', '0162_sessionprojecttag_meta_category_and_more'),
    ]

    operations = [
    ]
