# Generated by Django 5.2.15 on 2026-07-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0163_merge_20260624_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textscorevalues',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='numericalscorevalues',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='computedsetcomputedmolecule',
            name='computed_molecule',
        ),
        migrations.RemoveField(
            model_name='siteobservation',
            name='computed_molecules',
        ),
        migrations.RemoveField(
            model_name='siteobservationcomputedmolecule',
            name='computed_molecule',
        ),
        migrations.RemoveField(
            model_name='computedset',
            name='computed_molecules',
        ),
        migrations.RemoveField(
            model_name='computedsetcomputedmolecule',
            name='computed_set',
        ),
        migrations.RemoveField(
            model_name='numericalscorevalues',
            name='score',
        ),
        migrations.RemoveField(
            model_name='scoredescription',
            name='computed_set',
        ),
        migrations.RemoveField(
            model_name='textscorevalues',
            name='score',
        ),
        migrations.RemoveField(
            model_name='siteobservationcomputedmolecule',
            name='site_observation',
        ),
        migrations.DeleteModel(
            name='ComputedMolecule',
        ),
        migrations.DeleteModel(
            name='ComputedSetComputedMolecule',
        ),
        migrations.DeleteModel(
            name='NumericalScoreValues',
        ),
        migrations.DeleteModel(
            name='ScoreDescription',
        ),
        migrations.DeleteModel(
            name='TextScoreValues',
        ),
        migrations.DeleteModel(
            name='SiteObservationComputedMolecule',
        ),
    ]
