# Generated by Django 5.2.15 on 2026-07-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0165_downloadlinks_file_url_not_unique'),
        ('viewer', '0169_compound_stereo_inchi_key'),
    ]

    operations = [
    ]
