# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_version', models.CharField(choices=[(b'DE', b'Default'), (b'PR', b'Proasis')], default=b'DE', max_length=2)),
                ('interaction_type', models.CharField(choices=[(b'UK', b'Unkwnon'), (b'HB', b'H-bond'), (b'CP', b'Cation Pi'), (b'HA', b'Halogen'), (b'VD', b'Van der Waals'), (b'CH', b'Charge'), (b'WB', b'Weak H-bond'), (b'CD', b'Cation Dipole'), (b'HP', b'H-bond donor Pi'), (b'DI', b'Dipolar'), (b'PP', b'Pi Pi'), (b'PA', b'Poor angle'), (b'UF', b'Unfavourable')], default=b'UK', max_length=2)),
                ('distance', models.FloatField(null=True)),
                ('score', models.FloatField(null=True)),
                ('prot_smarts', models.TextField(null=True)),
                ('mol_smarts', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_atom_name', models.CharField(max_length=255)),
                ('molecule_atom_name', models.CharField(max_length=255)),
                ('mol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Molecule')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinResidue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='TargetResidue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=20)),
                ('res_num', models.IntegerField()),
                ('chain_id', models.CharField(max_length=4)),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Target')),
            ],
            options={
                'permissions': (('view_targetresidue', 'View targetresidue'),),
            },
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[(b'AD', b'Addition'), (b'DE', b'Deletion'), (b'LI', b'Linker'), (b'RI', b'Ring')], max_length=2)),
                ('cmpd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Compound')),
            ],
        ),
        migrations.CreateModel(
            name='Vector3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('start_x', models.FloatField(null=True)),
                ('start_y', models.FloatField(null=True)),
                ('start_z', models.FloatField(null=True)),
                ('end_x', models.FloatField(null=True)),
                ('end_y', models.FloatField(null=True)),
                ('end_z', models.FloatField(null=True)),
                ('mol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Molecule')),
                ('vector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypothesis.Vector')),
            ],
        ),
        migrations.AddField(
            model_name='proteinresidue',
            name='targ_res_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypothesis.TargetResidue'),
        ),
        migrations.AddField(
            model_name='interactionpoint',
            name='prot_res_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypothesis.ProteinResidue'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='interaction_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypothesis.InteractionPoint'),
        ),
        migrations.AlterUniqueTogether(
            name='vector3d',
            unique_together=set([('mol_id', 'vector_id', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='vector',
            unique_together=set([('cmpd_id', 'smiles', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='targetresidue',
            unique_together=set([('target_id', 'res_num', 'res_name', 'chain_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='proteinresidue',
            unique_together=set([('prot_id', 'targ_res_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='interactionpoint',
            unique_together=set([('prot_res_id', 'mol_id', 'protein_atom_name', 'molecule_atom_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together=set([('interaction_type', 'interaction_version', 'interaction_point')]),
        ),
    ]
