# Generated by Django 3.2.20 on 2023-08-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('viewer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('smiles', models.CharField(max_length=255)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('AD', 'Addition'),
                            ('DE', 'Deletion'),
                            ('LI', 'Linker'),
                            ('RI', 'Ring'),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    'cmpd_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.compound',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Vector3D',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number', models.IntegerField()),
                ('start_x', models.FloatField(null=True)),
                ('start_y', models.FloatField(null=True)),
                ('start_z', models.FloatField(null=True)),
                ('end_x', models.FloatField(null=True)),
                ('end_y', models.FloatField(null=True)),
                ('end_z', models.FloatField(null=True)),
                (
                    'site_observation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.siteobservation',
                    ),
                ),
                (
                    'vector',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='hypothesis.vector',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TargetResidue',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('res_name', models.CharField(max_length=20)),
                ('res_num', models.IntegerField()),
                ('chain_id', models.CharField(max_length=4)),
                (
                    'target_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='viewer.target'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='InteractionPoint',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('protein_atom_name', models.CharField(max_length=255)),
                ('molecule_atom_name', models.CharField(max_length=255)),
                (
                    'site_observation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.siteobservation',
                    ),
                ),
                (
                    'targ_res',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='hypothesis.targetresidue',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'interaction_version',
                    models.CharField(
                        choices=[('DE', 'Default'), ('PR', 'Proasis')],
                        default='DE',
                        max_length=2,
                    ),
                ),
                (
                    'interaction_type',
                    models.CharField(
                        choices=[
                            ('UK', 'Unkwnon'),
                            ('HB', 'H-bond'),
                            ('CP', 'Cation Pi'),
                            ('HA', 'Halogen'),
                            ('VD', 'Van der Waals'),
                            ('CH', 'Charge'),
                            ('WB', 'Weak H-bond'),
                            ('CD', 'Cation Dipole'),
                            ('HP', 'H-bond donor Pi'),
                            ('DI', 'Dipolar'),
                            ('PP', 'Pi Pi'),
                            ('PA', 'Poor angle'),
                            ('UF', 'Unfavourable'),
                        ],
                        default='UK',
                        max_length=2,
                    ),
                ),
                ('distance', models.FloatField(null=True)),
                ('score', models.FloatField(null=True)),
                ('prot_smarts', models.TextField(null=True)),
                ('mol_smarts', models.TextField(null=True)),
                (
                    'interaction_point',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='hypothesis.interactionpoint',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='vector3d',
            constraint=models.UniqueConstraint(
                fields=('site_observation', 'vector', 'number'),
                name='unique_siteobvs_vector_number',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='vector',
            unique_together={('cmpd_id', 'smiles', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='targetresidue',
            unique_together={('target_id', 'res_num', 'res_name', 'chain_id')},
        ),
        migrations.AddConstraint(
            model_name='interactionpoint',
            constraint=models.UniqueConstraint(
                fields=('site_observation', 'protein_atom_name', 'molecule_atom_name'),
                name='unique_siteobvs_protatom_molatom',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={
                ('interaction_type', 'interaction_version', 'interaction_point')
            },
        ),
    ]
