# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('UK', 'Unkwnon'), ('HB', 'H-bond'), ('CP', 'Cation Pi'), ('HA', 'Halogen'), ('VD', 'Van der Waals'), ('CH', 'Charge'), ('WB', 'Weak H-bond'), ('CD', 'Cation Dipole'), ('HP', 'H-bond donor Pi'), ('DI', 'Dipolar'), ('PP', 'Pi Pi'), ('PA', 'Poor angle'), ('UF', 'Unfavourable')], default='UK', max_length=2),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_version',
            field=models.CharField(choices=[('DE', 'Default'), ('PR', 'Proasis')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='vector',
            name='type',
            field=models.CharField(choices=[('AD', 'Addition'), ('DE', 'Deletion'), ('LI', 'Linker'), ('RI', 'Ring')], max_length=2),
        ),
    ]
