# Generated by Django 3.1 on 2020-08-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0002_auto_20200804_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetresidue',
            options={},
        ),
    ]
