# Generated by Django 3.2.20 on 2023-08-16 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0041_auto_20230726_0900'),
        ('hypothesis', '0003_auto_20200804_1411'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proteinresidue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='proteinresidue',
            name='prot_id',
        ),
        migrations.RemoveField(
            model_name='proteinresidue',
            name='targ_res_id',
        ),
        migrations.RenameField(
            model_name='vector3d',
            old_name='vector_id',
            new_name='vector',
        ),
        migrations.AddField(
            model_name='interactionpoint',
            name='site_observation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interactionpoint',
            name='targ_res',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hypothesis.targetresidue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vector3d',
            name='site_observation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='interactionpoint',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vector3d',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='interactionpoint',
            constraint=models.UniqueConstraint(fields=('site_observation', 'protein_atom_name', 'molecule_atom_name'), name='unique_siteobvs_protatom_molatom'),
        ),
        migrations.AddConstraint(
            model_name='vector3d',
            constraint=models.UniqueConstraint(fields=('site_observation', 'vector', 'number'), name='unique_siteobvs_vector_number'),
        ),
        migrations.RemoveField(
            model_name='interactionpoint',
            name='mol_id',
        ),
        migrations.RemoveField(
            model_name='interactionpoint',
            name='prot_res_id',
        ),
        migrations.RemoveField(
            model_name='vector3d',
            name='mol_id',
        ),
        migrations.DeleteModel(
            name='ProteinResidue',
        ),
    ]
