---
minimum_pre_commit_version: 3.1.1

repos:

# pre-commit hooks
# ----------

# Standard pre-commit rules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md

# MyPy
#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v1.7.1
#  hooks:
#  - id: mypy
#    additional_dependencies:
#    - types-PyYAML
#    - types-pytz
#    - types-python-dateutil
#    - types-requests

# Black (uncompromising) Python code formatter
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
    args:
    - --skip-string-normalization
    - --target-version
    - py311

# Pylint
- repo: https://github.com/pycqa/pylint
  rev: v2.17.7
  hooks:
  - id: pylint
    additional_dependencies:
    - pylint-django
    args:
    - --load-plugins
    - pylint_django,pylint_django.checkers.migrations
    - --django-settings-module
    - fragalysis.settings
