sudo: required
services:
  - docker
install:
  - docker build -t xchem/fragalysis-backend .
script:
  -  docker-compose -f docker-compose.test.yml up --build  --exit-code-from tests --abort-on-container-exit
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push xchem/fragalysis-backend;
    fi
  - coveralls


