---
# A 'common' set of services used (extended) by other docker-compose files.
services:

  # The database
  database:
    image: xchem/fragalysis-database:2026.04.1
    container_name: database
    volumes:
    - ./data/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: fragalysis
      POSTGRES_DB: frag
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -d frag
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 10s

  # Redis (Celery/Worker Broker)
  redis:
    image: redis:7.2.3-alpine3.18
    container_name: redis
    volumes:
    - ./data/redis/data:/data
    ports:
    - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 10s
