# Generated by Django 3.2.25 on 2024-05-17 13:56

from sys import displayhook
from django.db import migrations

states = ['NOT_CONFIGURED', 'DEGRADED', 'OK', 'ERROR']

def populate_states(apps, schema_editor):
    ServiceState = apps.get_model('service_status', 'ServiceState')
    for state in states:
        try:
            _ = ServiceState.objects.get(state=state)
        except ServiceState.DoesNotExist:
            ServiceState(
                state=state,
                display_name=state.lower().replace('_', ' '),
            ).save()

def drop_states(apps, schema_editor):
    ServiceState = apps.get_model('service_status', 'ServiceState')
    ServiceState.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_states, drop_states),
    ]
