# Generated by Django 3.2.25 on 2024-05-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0002_auto_20240517_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
