# Generated by Django 3.2.25 on 2024-05-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0003_rename_services_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestate',
            name='id',
        ),
        migrations.AlterField(
            model_name='servicestate',
            name='state',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
