# Generated by Django 3.2.25 on 2024-05-17 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0005_remove_service_last_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_state',
            field=models.ForeignKey(default='NOT_CONFIGURED', on_delete=django.db.models.deletion.PROTECT, to='service_status.servicestate'),
        ),
    ]
