# Generated by Django 3.2.25 on 2024-05-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0006_service_last_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='last_states_of_same_type',
            field=models.IntegerField(default=0),
        ),
    ]
