# Generated by Django 3.2.25 on 2024-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0007_alter_service_last_states_of_same_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='total_queries',
            field=models.IntegerField(default=0),
        ),
    ]
