labware_plates = {
    "4welltrough_4_reservoir_60000µL": {
        "type": ["solvent"],
        "no_wells": 4,
        "volume_well": 60000,
        "max_temp": 110,
        "reflux": False,
    },
    "8welltrough_8_reservoir_25000ul": {
        "type": ["solvent"],
        "no_wells": 8,
        "volume_well": 25000,
        "max_temp": 110,
        "reflux": False,
    },
    "12welltrough_12_reservoir_18000ul": {
        "type": ["solvent"],
        "no_wells": 12,
        "volume_well": 18000,
        "max_temp": 110,
        "reflux": False,
    },
    "24_reservoir_2500ul": {
        "type": ["startingmaterial", "solvent"],
        "no_wells": 24,
        "volume_well": 2500,
        "max_temp": 110,
        "reflux": False,
    },
    "labcyte_384_wellplate_100ul": {
        "type": ["lcms"],
        "no_wells": 384,
        "volume_well": 100,
        "max_temp": 110,
        "reflux": False,
    },
    "plateone_96_wellplate_500ul": {
        "type": ["reaction", "lcms", "xchem"],
        "no_wells": 96,
        "volume_well": 500,
        "max_temp": 110,
        "reflux": False,
    },
    "plateone_96_wellplate_2500ul": {
        "type": ["solvent", "reaction", "workup1", "workup2", "workup3"],
        "no_wells": 96,
        "volume_well": 2500,
        "max_temp": 110,
        "reflux": False,
    },
    "qmx_96_aluminumblock_962ul": {
        "type": ["reaction"],
        "no_wells": 96,
        "volume_well": 962,
        "max_temp": 250,
        "reflux": True,
    },
}
