# Generated by Django 3.1 on 2022-11-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='clonewellid',
        ),
        migrations.AddField(
            model_name='target',
            name='concentration',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='volume',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
