# Generated by Django 3.1 on 2022-11-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20221115_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaction',
            name='mass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addaction',
            name='massunit',
            field=models.CharField(choices=[('mg', 'Mg'), ('g', 'G')], default='mg', max_length=2),
        ),
        migrations.AlterField(
            model_name='addaction',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
