# Generated by Django 3.1 on 2022-11-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20221121_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mixaction',
            name='calcunit',
        ),
        migrations.RemoveField(
            model_name='mixaction',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='mixaction',
            name='volumeunit',
        ),
    ]
