# Generated by Django 3.1 on 2023-02-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20230201_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsession',
            name='type',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('stir', 'Stir'), ('workup1', 'Workup1'), ('workup2', 'Workup2'), ('workup3', 'Workup3'), ('analyse', 'Analyse')], max_length=10),
        ),
    ]
