# Generated by Django 3.2.20 on 2023-08-18 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('viewer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotMap',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'map_type',
                    models.CharField(
                        choices=[('AC', 'Acceptor'), ('AP', 'Apolar'), ('DO', 'Donor')],
                        max_length=2,
                    ),
                ),
                (
                    'map_info',
                    models.FileField(max_length=255, null=True, upload_to='maps/'),
                ),
                (
                    'compressed_map_info',
                    models.FileField(max_length=255, null=True, upload_to='maps/'),
                ),
                (
                    'site_observation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.siteobservation',
                    ),
                ),
                (
                    'target',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='viewer.target'
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='hotspotmap',
            constraint=models.UniqueConstraint(
                fields=('map_type', 'target', 'site_observation'),
                name='unique_maptype_target_siteobvs',
            ),
        ),
    ]
