# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspotmap',
            name='compressed_map_info',
            field=models.FileField(max_length=255, null=True, upload_to='maps/'),
        ),
        migrations.AlterField(
            model_name='hotspotmap',
            name='map_info',
            field=models.FileField(max_length=255, null=True, upload_to='maps/'),
        ),
        migrations.AlterField(
            model_name='hotspotmap',
            name='map_type',
            field=models.CharField(choices=[('AC', 'Acceptor'), ('AP', 'Apolar'), ('DO', 'Donor')], max_length=2),
        ),
    ]
