# Generated by Django 3.2.20 on 2023-08-16 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0041_auto_20230726_0900'),
        ('hotspots', '0002_auto_20200804_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotspotmap',
            old_name='target_id',
            new_name='target',
        ),
        migrations.AddField(
            model_name='hotspotmap',
            name='site_observation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hotspotmap',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='hotspotmap',
            constraint=models.UniqueConstraint(fields=('map_type', 'target', 'site_observation'), name='unique_maptype_target_siteobvs'),
        ),
        migrations.RemoveField(
            model_name='hotspotmap',
            name='prot_id',
        ),
    ]
