from django import forms

CSET_CHOICES = [
    ('V', 'Validate'),
    ('U', 'Upload'),
    ('D', 'Delete'),
]

TSET_CHOICES = [
    ('V', 'Validate'),
    ('U', 'Upload'),
]


class CSetForm(forms.Form):
    """Used for uploading Computed sets at viewer/upload_cset"""

    proposal_ref = forms.CharField(required=False, label='Proposal', max_length=200)
    target_name = forms.CharField(label='Target', max_length=100, required=False)
    sdf_file = forms.FileField(label='All compounds sdf (.sdf)', required=False)
    pdb_zip = forms.FileField(label='PDB files (.zip)', required=False)
    submit_choice = forms.CharField(widget=forms.RadioSelect(choices=CSET_CHOICES))
    # The upload_key was removed as part of development if issue-859,
    # the phase 2 Job launcher,
    # The user-specific 'upload_key' is/was key generated by `viewer.views.cset_key`
