# Generated by Django 3.2.20 on 2023-08-18 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('viewer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewScene',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('uuid', models.UUIDField(unique=True)),
                ('title', models.CharField(default='NA', max_length=200)),
                ('scene', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'snapshot',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.snapshot',
                    ),
                ),
                (
                    'user_id',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SiteObservationGroup',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'group_type',
                    models.CharField(
                        choices=[
                            ('PA', 'Pandda'),
                            ('DE', 'Default'),
                            ('MC', 'MolCluster'),
                            ('WC', 'WaterCluster'),
                            ('PC', 'PharmaCluster'),
                            ('RC', 'ResCluster'),
                        ],
                        default='DE',
                        max_length=2,
                    ),
                ),
                ('description', models.TextField(null=True)),
                ('x_com', models.FloatField(null=True)),
                ('y_com', models.FloatField(null=True)),
                ('z_com', models.FloatField(null=True)),
                (
                    'site_observation',
                    models.ManyToManyField(
                        related_name='site_observation_groups',
                        to='viewer.SiteObservation',
                    ),
                ),
                (
                    'target',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='viewer.target'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SiteObservationChoice',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'choice_type',
                    models.CharField(
                        choices=[
                            ('DE', 'Default'),
                            ('PA', 'Pandda'),
                            ('GM', 'Good molecule'),
                        ],
                        default='DE',
                        max_length=2,
                    ),
                ),
                ('score', models.FloatField(null=True)),
                (
                    'site_observation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.siteobservation',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SiteObservationAnnotation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('annotation_type', models.CharField(max_length=50)),
                ('annotation_text', models.CharField(max_length=100)),
                (
                    'site_observation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.siteobservation',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ScoreChoice',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_done', models.BooleanField(default=False)),
                (
                    'choice_type',
                    models.CharField(
                        choices=[
                            ('DE', 'Default'),
                            ('AU', 'Docking'),
                            ('IT', 'Interaction fit'),
                            ('DF', 'Density Fit'),
                        ],
                        default='DE',
                        max_length=2,
                    ),
                ),
                ('score', models.FloatField(null=True)),
                (
                    'site_observation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.siteobservation',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CmpdChoice',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'choice_type',
                    models.CharField(
                        choices=[('DE', 'Default'), ('PR', 'Price'), ('TO', 'Toxic')],
                        default='DE',
                        max_length=2,
                    ),
                ),
                ('score', models.FloatField(null=True)),
                (
                    'cmpd_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.compound',
                    ),
                ),
                (
                    'user_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='siteobservationchoice',
            constraint=models.UniqueConstraint(
                fields=('user_id', 'site_observation', 'choice_type'),
                name='unique_siteobvs_choice',
            ),
        ),
        migrations.AddConstraint(
            model_name='siteobservationannotation',
            constraint=models.UniqueConstraint(
                fields=('site_observation', 'annotation_type'),
                name='unique_siteobvs_anntype',
            ),
        ),
        migrations.AddConstraint(
            model_name='scorechoice',
            constraint=models.UniqueConstraint(
                fields=('user', 'site_observation', 'choice_type'),
                name='unique_user_siteobvs_dockchoice',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='cmpdchoice',
            unique_together={('user_id', 'cmpd_id', 'choice_type')},
        ),
    ]
