# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpdchoice',
            name='choice_type',
            field=models.CharField(choices=[('DE', 'Default'), ('PR', 'Price'), ('TO', 'Toxic')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='molchoice',
            name='choice_type',
            field=models.CharField(choices=[('DE', 'Default'), ('PA', 'Pandda'), ('GM', 'Good molecule')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='molgroup',
            name='group_type',
            field=models.CharField(choices=[('PA', 'Pandda'), ('DE', 'Default'), ('MC', 'MolCluster'), ('WC', 'WaterCluster'), ('PC', 'PharmaCluster'), ('RC', 'ResCluster')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='protchoice',
            name='choice_type',
            field=models.CharField(choices=[('DE', 'Default')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='scorechoice',
            name='choice_type',
            field=models.CharField(choices=[('DE', 'Default'), ('AU', 'Docking'), ('IT', 'Interaction fit'), ('DF', 'Density Fit')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='viewscene',
            name='title',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
