# Generated by Django 3.2.20 on 2023-10-20 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('viewer', '0013_auto_20230921_1417'),
        ('scoring', '0002_auto_20230818_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteObvsSiteObservationGroup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'site_observation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='viewer.siteobservation',
                    ),
                ),
                (
                    'site_obvs_group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='scoring.siteobservationgroup',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='siteobvssiteobservationgroup',
            constraint=models.UniqueConstraint(
                fields=('site_observation', 'site_obvs_group'),
                name='unique_siteobservationgroupcontents',
            ),
        ),
    ]
