# Generated by Django 3.2.20 on 2023-08-16 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0041_auto_20230726_0900'),
        ('scoring', '0003_auto_20200804_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteObservationChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_type', models.CharField(choices=[('DE', 'Default'), ('PA', 'Pandda'), ('GM', 'Good molecule')], default='DE', max_length=2)),
                ('score', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteObservationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('PA', 'Pandda'), ('DE', 'Default'), ('MC', 'MolCluster'), ('WC', 'WaterCluster'), ('PC', 'PharmaCluster'), ('RC', 'ResCluster')], default='DE', max_length=2)),
                ('description', models.TextField(null=True)),
                ('x_com', models.FloatField(null=True)),
                ('y_com', models.FloatField(null=True)),
                ('z_com', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MolAnnotation',
            new_name='SiteObservationAnnotation',
        ),
        migrations.AlterUniqueTogether(
            name='molchoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='molchoice',
            name='mol_id',
        ),
        migrations.RemoveField(
            model_name='molchoice',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='molgroup',
            name='mol_id',
        ),
        migrations.RemoveField(
            model_name='molgroup',
            name='target_id',
        ),
        migrations.AlterUniqueTogether(
            name='protchoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='protchoice',
            name='prot_id',
        ),
        migrations.RemoveField(
            model_name='protchoice',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='scorechoice',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='scorechoice',
            name='site_observation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteobservationannotation',
            name='site_observation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='scorechoice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='siteobservationannotation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='scorechoice',
            constraint=models.UniqueConstraint(fields=('user', 'site_observation', 'choice_type'), name='unique_user_siteobvs_dockchoice'),
        ),
        migrations.AddConstraint(
            model_name='siteobservationannotation',
            constraint=models.UniqueConstraint(fields=('site_observation', 'annotation_type'), name='unique_siteobvs_anntype'),
        ),
        migrations.DeleteModel(
            name='MolChoice',
        ),
    ]
