# Generated by Django 3.2.20 on 2023-10-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_auto_20230921_1417'),
        ('scoring', '0003_auto_20231020_1501'),
    ]

    # NB! had some trouble with autmoatically generated AlterField, so
    # changed it to remove + add
    operations = [
        migrations.RemoveField(
            model_name='siteobservationgroup',
            name='site_observation',
        ),
        migrations.AddField(
            model_name='siteobservationgroup',
            name='site_observation',
            field=models.ManyToManyField(related_name='site_observation_groups', through='scoring.SiteObvsSiteObservationGroup', to='viewer.SiteObservation'),
        ),        
    ]
