# Generated by Django 5.2.7 on 2025-10-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_alter_siteobservationgroup_site_observation'),
        ('viewer', '0147_alter_atomcoordinates_atom_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteobservationgroup',
            name='site_observation',
            field=models.ManyToManyField(related_name='site_observation_groups', through='scoring.SiteObvsSiteObservationGroup', through_fields=('site_obvs_group', 'site_observation'), to='viewer.siteobservation'),
        ),
    ]
