# Generated by Django 3.2.20 on 2023-08-16 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0042_auto_20230816_1208'),
        ('scoring', '0004_auto_20230816_1208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='MolGroup',
        ),
        migrations.DeleteModel(
            name='ProtChoice',
        ),
        migrations.AddField(
            model_name='siteobservationgroup',
            name='site_observation',
            field=models.ManyToManyField(related_name='site_observation_groups', to='viewer.SiteObservation'),
        ),
        migrations.AddField(
            model_name='siteobservationgroup',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.target'),
        ),
        migrations.AddField(
            model_name='siteobservationchoice',
            name='site_observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.siteobservation'),
        ),
        migrations.AddField(
            model_name='siteobservationchoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='scorechoice',
            name='mol_id',
        ),
        migrations.RemoveField(
            model_name='scorechoice',
            name='prot_id',
        ),
        migrations.RemoveField(
            model_name='siteobservationannotation',
            name='mol_id',
        ),
        migrations.AddConstraint(
            model_name='siteobservationchoice',
            constraint=models.UniqueConstraint(fields=('user_id', 'site_observation', 'choice_type'), name='unique_siteobvs_choice'),
        ),
    ]
