# Generated by Django 3.2.20 on 2023-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0044_auto_20230818_0928'),
        ('scoring', '0005_auto_20230816_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteobservationgroup',
            name='site_observation',
            field=models.ManyToManyField(related_name='site_observation_groups', to='viewer.SiteObservation'),
        ),
    ]
