# Generated by Django 3.2.20 on 2023-08-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0045_auto_20230818_0933'),
        ('scoring', '0006_alter_siteobservationgroup_site_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteobservationgroup',
            name='site_observation',
            field=models.ManyToManyField(related_name='site_observation_groups', to='viewer.SiteObservation'),
        ),
    ]
