---
version: '3'

services:

  # The database
  database:
    image: postgres:12.2
    container_name: database
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    - ./backup-dumpall.sql:/backup-dumpall.sql
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      #POSTGRES_DB: frag
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
