---
name: build dev

# Actions that take place after every commit to 'dev' branches
# Anything that's not staging or production.
#
# If a DOCKERHUB_USERNAME secret is defined the image is pushed.

# ---------------
# Control secrets
# ---------------
#
# At the GitHub 'organisation' or 'project' level you are expected to
# have the following GitHub 'Repository Secrets' defined
# (i.e. via 'Settings -> Secrets'): -
#
# BE_NAMESPACE            optional - default xchem
#
# DOCKERHUB_USERNAME      optional
# DOCKERHUB_TOKEN         optional - required if DOCKERHUB_USERNAME
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# (none)

on:
  push:
    branches-ignore:
    - 'staging'
    - 'production'
    tags-ignore:
    - '**'

env:
  # The following 'defaults' are used in the 'Initialise workflow variables' step,
  # which creates 'outputs' for use in steps and jobs that follow it.
  # The values set here are used unless a matching secret is found.
  # Secrets are the way users dynamically control the behaviour of this Action.
  #
  #   For Jobs conditional on the presence of a secret see this Gist...
  #   https://gist.github.com/jonico/24ffebee6d2fa2e679389fac8aef50a3
  BE_NAMESPACE: xchem

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      push: ${{ steps.vars.outputs.push }}
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v5
    - name: Initialise workflow variables
      id: vars
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        TRIGGER_DOWNSTREAM: ${{ secrets.TRIGGER_DOWNSTREAM }}
      run: |
        # BE_NAMESPACE
        BE_NAMESPACE="${{ env.BE_NAMESPACE }}"
        if [ -n "${{ secrets.BE_NAMESPACE }}" ]; then BE_NAMESPACE="${{ secrets.BE_NAMESPACE }}"; fi
        echo BE_NAMESPACE=${BE_NAMESPACE}
        echo "BE_NAMESPACE=${BE_NAMESPACE}" >> $GITHUB_OUTPUT

        # Do we push, i.e. is DOCKERHUB_USERNAME defined?
        echo push=${{ env.DOCKERHUB_USERNAME != '' }}
        echo "push=${{ env.DOCKERHUB_USERNAME != '' }}" >> $GITHUB_OUTPUT
    - name: Checkout
      uses: actions/checkout@v6
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.3.0
      with:
        dockerfile: Dockerfile
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - name: Run pre-commit (all files)
      run: |
        pip install --requirement build-requirements.txt
        pre-commit run --all-files
    - name: Docker build
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ steps.vars.outputs.BE_NAMESPACE }}/fragalysis-backend:${{ env.GITHUB_REF_SLUG }}
    - name: Display
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ steps.vars.outputs.BE_NAMESPACE }}/fragalysis-backend:${{ env.GITHUB_REF_SLUG }}
    - name: Display trivy templates
      run: |
        ls -l "${{ github.workspace }}/trivy/templates"
        cat "${{ github.workspace }}/trivy/templates/markdown.tpl"
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.33.1
      with:
        scan-type: image
        image-ref: ${{ steps.vars.outputs.BE_NAMESPACE }}/fragalysis-backend:${{ env.GITHUB_REF_SLUG }}
        version: latest
        vuln-type: library
        scanners: vuln
        severity: CRITICAL,HIGH
        format: template
        template: "@${{ github.workspace }}/trivy/templates/markdown.tpl"
        output: trivy-results.md

    - name: Vulnerability Scan (OSV)
      # The vulnerability scan (using Google's OSV)
      # Allowed to fail (we force true) as it's used for information only
      # The generated "Common Vulnerability Scoring System (CVSS)"" values
      # are interpreted as...
      #
      # - None: 0.0 (No impact)
      # - Low: 0.1–3.9 (Minor risk)
      # - Medium: 4.0–6.9 (Moderate risk)
      # - High: 7.0–8.9 (Serious risk)
      # - Critical: 9.0–10.0 (Grave, severe risk)
      run: |
        wget https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64 -O osv-scanner
        chmod +x osv-scanner
        ./osv-scanner scan image ${{ steps.vars.outputs.BE_NAMESPACE }}/fragalysis-backend:${{ env.GITHUB_REF_SLUG }} \
            --format markdown --output scan.md || true
        cat scan.md >> $GITHUB_STEP_SUMMARY
    - name: Test (docker compose)
      uses: hoverkraft-tech/compose-action@v2.4.2
      with:
        compose-file: ./docker-compose.test.yml
        up-flags: --build --exit-code-from tests --abort-on-container-exit
      env:
        BE_NAMESPACE: ${{ steps.vars.outputs.BE_NAMESPACE }}
        BE_IMAGE_TAG: ${{ env.GITHUB_REF_SLUG }}
    - name: Login to DockerHub
      if: steps.vars.outputs.push == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push
      if: steps.vars.outputs.push == 'true'
      run: docker push ${{ steps.vars.outputs.BE_NAMESPACE }}/fragalysis-backend:${{ env.GITHUB_REF_SLUG }}
